import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

export const SCHEMA_VERSION = 1;
export const DOCFLOW_DIR = '.docflow';
export const CONFIG_FILE = 'config.json';
export const STATE_FILE = 'state.json';
export const RUNTIME_FILE = 'runtime.json';
export const PROJECT_FILE = 'project.md';
export const MANAGED_BEGIN = '<!-- DOCFLOW:START -->';
export const MANAGED_END = '<!-- DOCFLOW:END -->';
export const GENERATED_NOTICE = '<!-- Generated by DocFlow. Edit the repository source, not this block. -->';

export const STATUS_VALUES = new Set(['In progress', 'Waiting', 'Paused', 'Completed', 'Abandoned']);
const TERMINAL_STATUSES = new Set(['Completed', 'Abandoned']);

function clean(value, label, { required = false, max = 4000 } = {}) {
  const text = String(value ?? '').replace(/\0/g, '').trim();
  if (required && !text) throw new Error(`${label} is required`);
  if (text.length > max) throw new Error(`${label} exceeds ${max} characters`);
  return text;
}

function isoNow(now = new Date()) {
  return now instanceof Date ? now.toISOString() : new Date(now).toISOString();
}

function canonicalStatus(value, fallback = 'In progress') {
  const raw = clean(value ?? fallback, 'status', { required: true, max: 80 });
  const key = raw.toLowerCase().replace(/[_-]+/g, ' ').replace(/\s+/g, ' ');
  const aliases = new Map([
    ['in progress', 'In progress'], ['progress', 'In progress'], ['active', 'In progress'],
    ['waiting', 'Waiting'], ['waiting human', 'Waiting'], ['waiting for user', 'Waiting'],
    ['paused', 'Paused'], ['pause', 'Paused'],
    ['completed', 'Completed'], ['complete', 'Completed'], ['done', 'Completed'],
    ['abandoned', 'Abandoned'], ['cancelled', 'Abandoned'], ['canceled', 'Abandoned'],
  ]);
  const out = aliases.get(key) ?? raw;
  if (!STATUS_VALUES.has(out)) throw new Error(`Unsupported status: ${raw}`);
  return out;
}

export function atomicWrite(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true, mode: 0o700 });
  const temp = path.join(path.dirname(filePath), `.${path.basename(filePath)}.${process.pid}.${Date.now()}.tmp`);
  fs.writeFileSync(temp, content, { encoding: 'utf8', mode: 0o600 });
  fs.renameSync(temp, filePath);
}

export function resolveRepoRoot(cwd = process.cwd(), exec = execFileSync) {
  try {
    return String(exec('git', ['-C', path.resolve(cwd), 'rev-parse', '--show-toplevel'], {
      encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'],
    })).trim();
  } catch {
    throw new Error(`Not inside a git repository: ${path.resolve(cwd)}`);
  }
}

function gitOutput(repoRoot, args, exec = execFileSync, { allowFailure = false } = {}) {
  try {
    return String(exec('git', ['-C', repoRoot, ...args], {
      encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], maxBuffer: 32 * 1024 * 1024,
    }) ?? '');
  } catch (error) {
    if (allowFailure) return '';
    const detail = error?.stderr ? String(error.stderr).trim() : error?.message;
    throw new Error(`git ${args.join(' ')} failed${detail ? `: ${detail}` : ''}`);
  }
}

export function repositoryFingerprint(repoRoot, exec = execFileSync) {
  const root = path.resolve(repoRoot);
  const excludes = ['.', ':(exclude).docflow', ':(exclude).docflow/**'];
  const head = gitOutput(root, ['rev-parse', 'HEAD'], exec, { allowFailure: true }).trim() || 'UNBORN';
  const status = gitOutput(root, ['status', '--porcelain=v1', '-z', '--untracked-files=all', '--', ...excludes], exec);
  const unstaged = head === 'UNBORN'
    ? gitOutput(root, ['diff', '--binary', '--', ...excludes], exec)
    : gitOutput(root, ['diff', '--binary', 'HEAD', '--', ...excludes], exec);
  const staged = gitOutput(root, ['diff', '--cached', '--binary', '--', ...excludes], exec);
  const hash = createHash('sha256').update(head).update('\0').update(status).update('\0').update(unstaged).update('\0').update(staged);

  for (const entry of status.split('\0').filter(Boolean)) {
    if (!entry.startsWith('?? ')) continue;
    const rel = entry.slice(3);
    if (!rel || rel === DOCFLOW_DIR || rel.startsWith(`${DOCFLOW_DIR}/`)) continue;
    const full = path.join(root, rel);
    try {
      const stat = fs.statSync(full);
      if (!stat.isFile()) continue;
      hash.update('\0UNTRACKED\0').update(rel).update('\0').update(String(stat.size)).update('\0');
      if (stat.size <= 10 * 1024 * 1024) hash.update(fs.readFileSync(full));
    } catch {
      hash.update('\0MISSING\0').update(rel);
    }
  }
  return hash.digest('hex');
}

export function repoPaths(repoRoot) {
  const dir = path.join(repoRoot, DOCFLOW_DIR);
  return {
    dir,
    config: path.join(dir, CONFIG_FILE),
    state: path.join(dir, STATE_FILE),
    runtime: path.join(dir, RUNTIME_FILE),
    project: path.join(dir, PROJECT_FILE),
  };
}

function safeNotePath(value) {
  const note = clean(value, 'obsidianNote', { required: true, max: 300 }).replaceAll('\\', '/');
  if (path.posix.isAbsolute(note)) throw new Error('obsidianNote must be relative to the configured project folder');
  const normalized = path.posix.normalize(note);
  if (normalized === '..' || normalized.startsWith('../')) throw new Error('obsidianNote may not escape the project folder');
  if (!normalized.toLowerCase().endsWith('.md')) throw new Error('obsidianNote must be a Markdown file');
  return normalized;
}

export function defaultState() {
  return { schemaVersion: SCHEMA_VERSION, activeTaskId: null, tasks: [], updatedAt: null };
}

export function defaultRuntime() {
  return { schemaVersion: SCHEMA_VERSION, activeSession: null, lastCheckpoint: null };
}

function validateTask(task) {
  if (!task || typeof task !== 'object' || Array.isArray(task)) throw new Error('Invalid DocFlow task');
  task.id = clean(task.id, 'task.id', { required: true, max: 120 });
  task.title = clean(task.title, 'task.title', { required: true, max: 300 });
  task.task = clean(task.task, 'task.task', { required: true, max: 2000 });
  task.started = clean(task.started, 'task.started', { required: true, max: 80 });
  task.status = canonicalStatus(task.status);
  task.current = clean(task.current, 'task.current', { max: 2000 });
  task.next = clean(task.next, 'task.next', { max: 2000 });
  if (!Array.isArray(task.history) || task.history.length > 10000) throw new Error('Invalid DocFlow task history');
  task.history = task.history.map((entry) => {
    if (!entry || typeof entry !== 'object' || Array.isArray(entry)) throw new Error('Invalid DocFlow history entry');
    return { at: clean(entry.at, 'history.at', { required: true, max: 80 }), text: clean(entry.text, 'history.text', { required: true, max: 2000 }) };
  });
  task.completed = task.completed == null ? null : clean(task.completed, 'task.completed', { required: true, max: 80 });
  task.outcome = task.outcome == null ? null : clean(task.outcome, 'task.outcome', { required: true, max: 300 });
  return task;
}

export function validateState(state) {
  if (!state || typeof state !== 'object' || Array.isArray(state) || state.schemaVersion !== SCHEMA_VERSION) {
    throw new Error('Unsupported or invalid DocFlow state');
  }
  if (!Array.isArray(state.tasks) || state.tasks.length > 5000) throw new Error('Invalid DocFlow task list');
  const seen = new Set();
  state.tasks = state.tasks.map((task) => {
    const normalized = validateTask({ ...task });
    if (seen.has(normalized.id)) throw new Error(`Duplicate DocFlow task id: ${normalized.id}`);
    seen.add(normalized.id);
    return normalized;
  });
  state.activeTaskId = state.activeTaskId == null ? null : clean(state.activeTaskId, 'activeTaskId', { required: true, max: 120 });
  if (state.activeTaskId && !seen.has(state.activeTaskId)) throw new Error('activeTaskId does not exist');
  state.updatedAt = state.updatedAt == null ? null : clean(state.updatedAt, 'updatedAt', { required: true, max: 80 });
  return state;
}

export function validateRuntime(runtime) {
  if (!runtime || typeof runtime !== 'object' || Array.isArray(runtime) || runtime.schemaVersion !== SCHEMA_VERSION) {
    throw new Error('Unsupported or invalid DocFlow runtime state');
  }
  for (const key of ['activeSession', 'lastCheckpoint']) {
    if (runtime[key] != null && (typeof runtime[key] !== 'object' || Array.isArray(runtime[key]))) throw new Error(`Invalid ${key}`);
  }
  return runtime;
}

export function loadRepoConfig(repoRoot) {
  const { config } = repoPaths(repoRoot);
  if (!fs.existsSync(config)) return null;
  const value = JSON.parse(fs.readFileSync(config, 'utf8'));
  if (!value || typeof value !== 'object' || value.schemaVersion !== SCHEMA_VERSION) throw new Error('Unsupported DocFlow repo config');
  return {
    schemaVersion: SCHEMA_VERSION,
    projectName: clean(value.projectName, 'projectName', { required: true, max: 200 }),
    obsidianNote: safeNotePath(value.obsidianNote),
  };
}

export function loadState(repoRoot) {
  const { state } = repoPaths(repoRoot);
  return validateState(JSON.parse(fs.readFileSync(state, 'utf8')));
}

export function loadRuntime(repoRoot) {
  const { runtime } = repoPaths(repoRoot);
  if (!fs.existsSync(runtime)) return defaultRuntime();
  return validateRuntime(JSON.parse(fs.readFileSync(runtime, 'utf8')));
}

function writeState(repoRoot, state) {
  const normalized = validateState({ ...state, tasks: state.tasks.map((t) => ({ ...t, history: t.history.map((h) => ({ ...h })) })) });
  atomicWrite(repoPaths(repoRoot).state, `${JSON.stringify(normalized, null, 2)}\n`);
  return normalized;
}

function writeRuntime(repoRoot, runtime) {
  atomicWrite(repoPaths(repoRoot).runtime, `${JSON.stringify(validateRuntime(runtime), null, 2)}\n`);
  return runtime;
}

export function initRepo({ cwd = process.cwd(), projectName, summary = '', obsidianNote, now = new Date(), exec = execFileSync } = {}) {
  const repoRoot = resolveRepoRoot(cwd, exec);
  const paths = repoPaths(repoRoot);
  if (fs.existsSync(paths.config)) return { repoRoot, alreadyInitialized: true, config: loadRepoConfig(repoRoot) };
  const name = clean(projectName || path.basename(repoRoot), 'projectName', { required: true, max: 200 });
  const note = safeNotePath(obsidianNote || `project - ${name.toLowerCase()}.md`);
  fs.mkdirSync(paths.dir, { recursive: true, mode: 0o700 });
  atomicWrite(paths.config, `${JSON.stringify({ schemaVersion: SCHEMA_VERSION, projectName: name, obsidianNote: note }, null, 2)}\n`);
  atomicWrite(paths.state, `${JSON.stringify(defaultState(), null, 2)}\n`);
  atomicWrite(paths.runtime, `${JSON.stringify(defaultRuntime(), null, 2)}\n`);
  const projectBody = `# ${name}\n\n## Project\n${clean(summary, 'summary', { max: 2000 }) || '-'}\n\n## Project principles\n-\n`;
  atomicWrite(paths.project, projectBody);
  return { repoRoot, alreadyInitialized: false, config: loadRepoConfig(repoRoot), initializedAt: isoNow(now) };
}

export function startTask({ cwd = process.cwd(), id, title, task, current = '', next = '', status = 'In progress', now = new Date(), exec = execFileSync } = {}) {
  const repoRoot = resolveRepoRoot(cwd, exec);
  if (!loadRepoConfig(repoRoot)) throw new Error('DocFlow is not enabled in this repository');
  const state = loadState(repoRoot);
  const taskId = clean(id, 'task id', { required: true, max: 120 });
  if (state.tasks.some((entry) => entry.id === taskId)) throw new Error(`Task already exists: ${taskId}`);
  const entry = validateTask({
    id: taskId,
    title: clean(title, 'task title', { required: true, max: 300 }),
    task: clean(task, 'task description', { required: true, max: 2000 }),
    started: isoNow(now),
    status: canonicalStatus(status),
    current: clean(current, 'current', { max: 2000 }),
    next: clean(next, 'next', { max: 2000 }),
    history: [], completed: null, outcome: null,
  });
  state.tasks.push(entry);
  state.activeTaskId = taskId;
  state.updatedAt = isoNow(now);
  writeState(repoRoot, state);
  return { repoRoot, task: entry, state };
}

function findTask(state, id) {
  const taskId = clean(id || state.activeTaskId, 'task id', { required: true, max: 120 });
  const task = state.tasks.find((entry) => entry.id === taskId);
  if (!task) throw new Error(`Unknown DocFlow task: ${taskId}`);
  return task;
}

export function beginRound({ cwd = process.cwd(), id, now = new Date(), exec = execFileSync } = {}) {
  const repoRoot = resolveRepoRoot(cwd, exec);
  const state = loadState(repoRoot);
  const runtime = loadRuntime(repoRoot);
  const task = findTask(state, id);
  if (TERMINAL_STATUSES.has(task.status)) throw new Error(`Task ${task.id} is terminal (${task.status})`);
  const fingerprint = repositoryFingerprint(repoRoot, exec);
  if (runtime.activeSession) {
    if (runtime.activeSession.taskId === task.id && runtime.activeSession.baselineFingerprint === fingerprint) {
      return { repoRoot, session: runtime.activeSession, reused: true };
    }
    throw new Error(`DocFlow already has an uncheckpointed round for ${runtime.activeSession.taskId}`);
  }
  runtime.activeSession = { taskId: task.id, startedAt: isoNow(now), baselineFingerprint: fingerprint };
  writeRuntime(repoRoot, runtime);
  state.activeTaskId = task.id;
  state.updatedAt = isoNow(now);
  writeState(repoRoot, state);
  return { repoRoot, session: runtime.activeSession, reused: false };
}

export function checkpoint({ cwd = process.cwd(), id, current, next = '', status, outcome, now = new Date(), exec = execFileSync } = {}) {
  const repoRoot = resolveRepoRoot(cwd, exec);
  const state = loadState(repoRoot);
  const runtime = loadRuntime(repoRoot);
  const task = findTask(state, id || runtime.activeSession?.taskId);
  const newCurrent = clean(current, 'current', { required: true, max: 2000 });
  const newNext = clean(next, 'next', { max: 2000 });
  const newStatus = canonicalStatus(status ?? task.status);
  if (TERMINAL_STATUSES.has(task.status) && newStatus !== task.status) throw new Error(`Terminal task ${task.id} cannot be reopened in v1`);
  if (task.current && task.current !== newCurrent) {
    const last = task.history.at(-1)?.text;
    if (last !== task.current) task.history.push({ at: isoNow(now), text: task.current });
  }
  task.current = newCurrent;
  task.next = newNext;
  task.status = newStatus;
  if (TERMINAL_STATUSES.has(newStatus)) {
    task.completed ??= isoNow(now);
    task.outcome = outcome == null || !String(outcome).trim() ? task.outcome : clean(outcome, 'outcome', { max: 300 });
  } else if (outcome != null && String(outcome).trim()) {
    throw new Error('Outcome is only valid for a terminal task');
  }
  state.activeTaskId = task.id;
  state.updatedAt = isoNow(now);
  writeState(repoRoot, state);
  const fingerprint = repositoryFingerprint(repoRoot, exec);
  runtime.lastCheckpoint = { taskId: task.id, at: isoNow(now), fingerprint };
  runtime.activeSession = null;
  writeRuntime(repoRoot, runtime);
  return { repoRoot, task, state, runtime };
}

export function gateStatus({ cwd = process.cwd(), exec = execFileSync } = {}) {
  const repoRoot = resolveRepoRoot(cwd, exec);
  if (!loadRepoConfig(repoRoot)) return { repoRoot, enabled: false, status: 'DISABLED', reason: 'repository has no .docflow/config.json' };
  const runtime = loadRuntime(repoRoot);
  const fingerprint = repositoryFingerprint(repoRoot, exec);
  if (runtime.activeSession) {
    return { repoRoot, enabled: true, status: 'PENDING', reason: `uncheckpointed round for ${runtime.activeSession.taskId}`, taskId: runtime.activeSession.taskId };
  }
  if (!runtime.lastCheckpoint) {
    return { repoRoot, enabled: true, status: 'PENDING', reason: 'no successful checkpoint has been recorded yet', taskId: null };
  }
  if (runtime.lastCheckpoint.fingerprint !== fingerprint) {
    return { repoRoot, enabled: true, status: 'PENDING', reason: 'repository work changed after the last checkpoint', taskId: runtime.lastCheckpoint.taskId };
  }
  return { repoRoot, enabled: true, status: 'READY', reason: 'current repository work matches the last successful checkpoint', taskId: runtime.lastCheckpoint.taskId, checkpointAt: runtime.lastCheckpoint.at };
}

export function projectStatus({ cwd = process.cwd(), exec = execFileSync } = {}) {
  const repoRoot = resolveRepoRoot(cwd, exec);
  const config = loadRepoConfig(repoRoot);
  if (!config) return { repoRoot, enabled: false, gate: gateStatus({ cwd: repoRoot, exec }) };
  const state = loadState(repoRoot);
  return { repoRoot, enabled: true, config, state, gate: gateStatus({ cwd: repoRoot, exec }) };
}

export function renderProgress(state) {
  const normalized = validateState(JSON.parse(JSON.stringify(state)));
  const lines = [MANAGED_BEGIN, GENERATED_NOTICE, ''];
  if (!normalized.tasks.length) {
    lines.push('_No DocFlow version/task records yet._');
  }
  for (const task of normalized.tasks) {
    lines.push(`## ${task.id} · ${task.title}`, '');
    lines.push(`**Task:** ${task.task}`);
    lines.push(`**Started:** ${task.started}`);
    lines.push(`**Status:** ${task.status}`);
    lines.push('');
    lines.push('**Current**', task.current || '-', '');
    lines.push('**Next**', task.next || '-', '');
    lines.push('**History**');
    if (task.history.length) {
      for (const entry of task.history) lines.push(`- ${entry.text}`);
    } else {
      lines.push('-');
    }
    if (task.completed) lines.push('', `**Completed:** ${task.completed}`);
    if (task.outcome) lines.push(`**Outcome:** ${task.outcome}`);
    lines.push('');
  }
  while (lines.at(-1) === '') lines.pop();
  lines.push('', MANAGED_END);
  return `${lines.join('\n')}\n`;
}

function markerCount(text, marker) {
  return text.split(marker).length - 1;
}

export function upsertManagedBlock(existing, block) {
  const text = String(existing ?? '');
  const bc = markerCount(text, MANAGED_BEGIN);
  const ec = markerCount(text, MANAGED_END);
  if (bc === 0 && ec === 0) {
    const prefix = text.trimEnd();
    return `${prefix ? `${prefix}\n\n` : ''}${block.trimEnd()}\n`;
  }
  if (bc !== 1 || ec !== 1) throw new Error('Refusing to update malformed or duplicate DocFlow managed block');
  const start = text.indexOf(MANAGED_BEGIN);
  const endStart = text.indexOf(MANAGED_END);
  if (endStart < start) throw new Error('Refusing to update malformed DocFlow managed block');
  const end = endStart + MANAGED_END.length;
  return `${text.slice(0, start)}${block.trimEnd()}${text.slice(end)}`.replace(/\s*$/, '\n');
}

export function globalConfigPath(homeDir = os.homedir()) {
  return path.join(homeDir, '.docflow', 'config.json');
}

export function configureGlobal({ homeDir = os.homedir(), vault, projectFolder = '02 Projects' } = {}) {
  const vaultPath = path.resolve(clean(vault, 'vault', { required: true, max: 1000 }));
  const folderRaw = clean(projectFolder, 'projectFolder', { required: true, max: 500 }).replaceAll('\\', '/');
  if (path.posix.isAbsolute(folderRaw)) throw new Error('projectFolder must be relative to the vault');
  const folder = path.posix.normalize(folderRaw);
  if (folder === '..' || folder.startsWith('../')) throw new Error('projectFolder may not escape the vault');
  const config = { schemaVersion: SCHEMA_VERSION, obsidian: { vault: vaultPath, projectFolder: folder } };
  atomicWrite(globalConfigPath(homeDir), `${JSON.stringify(config, null, 2)}\n`);
  return config;
}

export function loadGlobalConfig(homeDir = os.homedir()) {
  const file = globalConfigPath(homeDir);
  if (!fs.existsSync(file)) return null;
  const value = JSON.parse(fs.readFileSync(file, 'utf8'));
  if (!value || value.schemaVersion !== SCHEMA_VERSION || typeof value.obsidian !== 'object') throw new Error('Unsupported DocFlow global config');
  return configureShape(value);
}

function configureShape(value) {
  const vault = path.resolve(clean(value.obsidian?.vault, 'vault', { required: true, max: 1000 }));
  const folderRaw = clean(value.obsidian?.projectFolder, 'projectFolder', { required: true, max: 500 }).replaceAll('\\', '/');
  if (path.posix.isAbsolute(folderRaw)) throw new Error('projectFolder must be relative to the vault');
  const folder = path.posix.normalize(folderRaw);
  if (folder === '..' || folder.startsWith('../')) throw new Error('projectFolder may not escape the vault');
  return { schemaVersion: SCHEMA_VERSION, obsidian: { vault, projectFolder: folder } };
}

export function syncObsidian({ cwd = process.cwd(), homeDir = os.homedir(), exec = execFileSync } = {}) {
  const repoRoot = resolveRepoRoot(cwd, exec);
  const repoConfig = loadRepoConfig(repoRoot);
  if (!repoConfig) throw new Error('DocFlow is not enabled in this repository');
  const global = loadGlobalConfig(homeDir);
  if (!global) return { skipped: true, reason: 'global Obsidian location is not configured' };
  const state = loadState(repoRoot);
  const projectSource = fs.existsSync(repoPaths(repoRoot).project) ? fs.readFileSync(repoPaths(repoRoot).project, 'utf8').trim() : '';
  const target = path.resolve(global.obsidian.vault, global.obsidian.projectFolder, repoConfig.obsidianNote);
  const allowedRoot = path.resolve(global.obsidian.vault, global.obsidian.projectFolder);
  if (target !== allowedRoot && !target.startsWith(`${allowedRoot}${path.sep}`)) throw new Error('Resolved Obsidian note escaped the configured project folder');
  const block = renderProgress(state);
  let created = false;
  let existing = '';
  if (fs.existsSync(target)) {
    existing = fs.readFileSync(target, 'utf8');
  } else {
    created = true;
    existing = `---\ntype: project\n---\n\n${projectSource ? `${projectSource}\n` : `# ${repoConfig.projectName}\n`}`;
  }
  const next = upsertManagedBlock(existing, block);
  atomicWrite(target, next);
  return { skipped: false, created, path: target };
}
