import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  STATE_BRANCH,
  commitStateFiles,
  listStateFiles,
  readStateFile,
  refreshStateFromOrigin,
  runtimePath,
  stateFileRevision,
  stateStoreStatus,
  stateUnitPath,
} from './state-store.js';

export const SCHEMA_VERSION = 1;
export const DOCFLOW_DIR = '.docflow';
export const CONFIG_FILE = 'config.json';
export const STATE_FILE = 'state.json';
export const RUNTIME_FILE = 'runtime.json';
export const PROJECT_FILE = 'project.md';
export const MANAGED_BEGIN = '<!-- DOCFLOW:START -->';
export const MANAGED_END = '<!-- DOCFLOW:END -->';
export const GENERATED_NOTICE = '<!-- Generated by DocFlow. Edit the repository source, not this block. -->';
const DURABLE_CONFIG_PATH = '.docflow/config.json';
const DURABLE_PROJECT_PATH = '.docflow/project.md';
const DURABLE_UNITS_PREFIX = '.docflow/units';

export const STATUS_VALUES = new Set(['In progress', 'Waiting', 'Paused', 'Completed', 'Abandoned']);
const TERMINAL_STATUSES = new Set(['Completed', 'Abandoned']);

function clean(value, label, { required = false, max = 4000 } = {}) {
  const text = String(value ?? '').replace(/\0/g, '').trim();
  if (required && !text) throw new Error(`${label} is required`);
  if (text.length > max) throw new Error(`${label} exceeds ${max} characters`);
  return text;
}

function isoNow(now = new Date()) {
  return now instanceof Date ? now.toISOString() : new Date(now).toISOString();
}

function canonicalStatus(value, fallback = 'In progress') {
  const raw = clean(value ?? fallback, 'status', { required: true, max: 80 });
  const key = raw.toLowerCase().replace(/[_-]+/g, ' ').replace(/\s+/g, ' ');
  const aliases = new Map([
    ['in progress', 'In progress'], ['progress', 'In progress'], ['active', 'In progress'],
    ['waiting', 'Waiting'], ['waiting human', 'Waiting'], ['waiting for user', 'Waiting'],
    ['paused', 'Paused'], ['pause', 'Paused'],
    ['completed', 'Completed'], ['complete', 'Completed'], ['done', 'Completed'],
    ['abandoned', 'Abandoned'], ['cancelled', 'Abandoned'], ['canceled', 'Abandoned'],
  ]);
  const out = aliases.get(key) ?? raw;
  if (!STATUS_VALUES.has(out)) throw new Error(`Unsupported status: ${raw}`);
  return out;
}

export function atomicWrite(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true, mode: 0o700 });
  const temp = path.join(path.dirname(filePath), `.${path.basename(filePath)}.${process.pid}.${Date.now()}.tmp`);
  fs.writeFileSync(temp, content, { encoding: 'utf8', mode: 0o600 });
  fs.renameSync(temp, filePath);
}

export function resolveRepoRoot(cwd = process.cwd(), exec = execFileSync) {
  try {
    return String(exec('git', ['-C', path.resolve(cwd), 'rev-parse', '--show-toplevel'], {
      encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'],
    })).trim();
  } catch {
    throw new Error(`Not inside a git repository: ${path.resolve(cwd)}`);
  }
}

function gitOutput(repoRoot, args, exec = execFileSync, { allowFailure = false } = {}) {
  try {
    return String(exec('git', ['-C', repoRoot, ...args], {
      encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], maxBuffer: 32 * 1024 * 1024,
    }) ?? '');
  } catch (error) {
    if (allowFailure) return '';
    const detail = error?.stderr ? String(error.stderr).trim() : error?.message;
    throw new Error(`git ${args.join(' ')} failed${detail ? `: ${detail}` : ''}`);
  }
}

export function repositoryFingerprint(repoRoot, exec = execFileSync) {
  const root = path.resolve(repoRoot);
  const excludes = ['.', ':(exclude).docflow', ':(exclude).docflow/**'];
  const head = gitOutput(root, ['rev-parse', 'HEAD'], exec, { allowFailure: true }).trim() || 'UNBORN';
  const status = gitOutput(root, ['status', '--porcelain=v1', '-z', '--untracked-files=all', '--', ...excludes], exec);
  const unstaged = head === 'UNBORN'
    ? gitOutput(root, ['diff', '--binary', '--', ...excludes], exec)
    : gitOutput(root, ['diff', '--binary', 'HEAD', '--', ...excludes], exec);
  const staged = gitOutput(root, ['diff', '--cached', '--binary', '--', ...excludes], exec);
  const hash = createHash('sha256').update(head).update('\0').update(status).update('\0').update(unstaged).update('\0').update(staged);

  for (const entry of status.split('\0').filter(Boolean)) {
    if (!entry.startsWith('?? ')) continue;
    const rel = entry.slice(3);
    if (!rel || rel === DOCFLOW_DIR || rel.startsWith(`${DOCFLOW_DIR}/`)) continue;
    const full = path.join(root, rel);
    try {
      const stat = fs.statSync(full);
      if (!stat.isFile()) continue;
      hash.update('\0UNTRACKED\0').update(rel).update('\0').update(String(stat.size)).update('\0');
      const fd = fs.openSync(full, 'r');
      try {
        const buffer = Buffer.allocUnsafe(1024 * 1024);
        let offset = 0;
        while (offset < stat.size) {
          const bytesRead = fs.readSync(fd, buffer, 0, Math.min(buffer.length, stat.size - offset), offset);
          if (bytesRead <= 0) break;
          hash.update(buffer.subarray(0, bytesRead));
          offset += bytesRead;
        }
      } finally {
        fs.closeSync(fd);
      }
    } catch {
      hash.update('\0MISSING\0').update(rel);
    }
  }
  return hash.digest('hex');
}

export function repoPaths(repoRoot) {
  const dir = path.join(repoRoot, DOCFLOW_DIR);
  return {
    dir,
    config: path.join(dir, CONFIG_FILE),
    state: path.join(dir, STATE_FILE),
    runtime: path.join(dir, RUNTIME_FILE),
    project: path.join(dir, PROJECT_FILE),
  };
}

function safeNotePath(value) {
  const note = clean(value, 'obsidianNote', { required: true, max: 300 }).replaceAll('\\', '/');
  if (path.posix.isAbsolute(note)) throw new Error('obsidianNote must be relative to the configured project folder');
  const normalized = path.posix.normalize(note);
  if (normalized === '..' || normalized.startsWith('../')) throw new Error('obsidianNote may not escape the project folder');
  if (!normalized.toLowerCase().endsWith('.md')) throw new Error('obsidianNote must be a Markdown file');
  return normalized;
}

export function defaultState() {
  return { schemaVersion: SCHEMA_VERSION, activeTaskId: null, tasks: [], updatedAt: null };
}

export function defaultRuntime() {
  return { schemaVersion: SCHEMA_VERSION, activeTaskId: null, activeSession: null, lastCheckpoint: null };
}

function validateTask(task) {
  if (!task || typeof task !== 'object' || Array.isArray(task)) throw new Error('Invalid DocFlow task');
  task.id = clean(task.id, 'task.id', { required: true, max: 120 });
  task.title = clean(task.title, 'task.title', { required: true, max: 300 });
  task.task = clean(task.task, 'task.task', { required: true, max: 2000 });
  task.started = clean(task.started, 'task.started', { required: true, max: 80 });
  task.status = canonicalStatus(task.status);
  task.current = clean(task.current, 'task.current', { max: 2000 });
  task.next = clean(task.next, 'task.next', { max: 2000 });
  if (!Array.isArray(task.history) || task.history.length > 10000) throw new Error('Invalid DocFlow task history');
  task.history = task.history.map((entry) => {
    if (!entry || typeof entry !== 'object' || Array.isArray(entry)) throw new Error('Invalid DocFlow history entry');
    return { at: clean(entry.at, 'history.at', { required: true, max: 80 }), text: clean(entry.text, 'history.text', { required: true, max: 2000 }) };
  });
  task.completed = task.completed == null ? null : clean(task.completed, 'task.completed', { required: true, max: 80 });
  task.outcome = task.outcome == null ? null : clean(task.outcome, 'task.outcome', { required: true, max: 300 });
  return task;
}

export function validateState(state) {
  if (!state || typeof state !== 'object' || Array.isArray(state) || state.schemaVersion !== SCHEMA_VERSION) {
    throw new Error('Unsupported or invalid DocFlow state');
  }
  if (!Array.isArray(state.tasks) || state.tasks.length > 5000) throw new Error('Invalid DocFlow task list');
  const seen = new Set();
  state.tasks = state.tasks.map((task) => {
    const normalized = validateTask({ ...task });
    if (seen.has(normalized.id)) throw new Error(`Duplicate DocFlow task id: ${normalized.id}`);
    seen.add(normalized.id);
    return normalized;
  });
  state.activeTaskId = state.activeTaskId == null ? null : clean(state.activeTaskId, 'activeTaskId', { required: true, max: 120 });
  if (state.activeTaskId && !seen.has(state.activeTaskId)) throw new Error('activeTaskId does not exist');
  state.updatedAt = state.updatedAt == null ? null : clean(state.updatedAt, 'updatedAt', { required: true, max: 80 });
  return state;
}

export function validateRuntime(runtime) {
  if (!runtime || typeof runtime !== 'object' || Array.isArray(runtime) || runtime.schemaVersion !== SCHEMA_VERSION) {
    throw new Error('Unsupported or invalid DocFlow runtime state');
  }
  runtime.activeTaskId = runtime.activeTaskId == null
    ? null
    : clean(runtime.activeTaskId, 'runtime.activeTaskId', { required: true, max: 120 });
  for (const key of ['activeSession', 'lastCheckpoint']) {
    if (runtime[key] != null && (typeof runtime[key] !== 'object' || Array.isArray(runtime[key]))) throw new Error(`Invalid ${key}`);
  }
  return runtime;
}

function normalizeRepoConfig(value) {
  if (!value || typeof value !== 'object' || value.schemaVersion !== SCHEMA_VERSION) throw new Error('Unsupported DocFlow repo config');
  return {
    schemaVersion: SCHEMA_VERSION,
    projectName: clean(value.projectName, 'projectName', { required: true, max: 200 }),
    obsidianNote: safeNotePath(value.obsidianNote),
  };
}

function parseDurableUnit(text, source) {
  const value = JSON.parse(text);
  if (!value || typeof value !== 'object' || value.schemaVersion !== SCHEMA_VERSION || !value.task) {
    throw new Error(`Unsupported DocFlow durable unit: ${source}`);
  }
  return {
    task: validateTask({ ...value.task, history: Array.isArray(value.task.history) ? value.task.history.map((h) => ({ ...h })) : value.task.history }),
    updatedAt: clean(value.updatedAt, 'unit.updatedAt', { required: true, max: 80 }),
  };
}

function durableConfigText(repoRoot, exec = execFileSync) {
  return readStateFile(repoRoot, DURABLE_CONFIG_PATH, exec);
}

export function loadRepoConfig(repoRoot, exec = execFileSync) {
  const durable = durableConfigText(repoRoot, exec);
  if (durable != null) return normalizeRepoConfig(JSON.parse(durable));

  const { config } = repoPaths(repoRoot);
  if (!fs.existsSync(config)) return null;
  return normalizeRepoConfig(JSON.parse(fs.readFileSync(config, 'utf8')));
}

export function loadState(repoRoot, exec = execFileSync) {
  const durableConfig = durableConfigText(repoRoot, exec);
  if (durableConfig != null) {
    const runtime = loadRuntime(repoRoot, exec);
    const unitPaths = listStateFiles(repoRoot, DURABLE_UNITS_PREFIX, exec);
    const units = unitPaths.map((unitPath) => {
      const text = readStateFile(repoRoot, unitPath, exec);
      if (text == null) throw new Error(`Missing DocFlow durable unit: ${unitPath}`);
      return parseDurableUnit(text, unitPath);
    });
    const updatedAt = units.map((unit) => unit.updatedAt).sort().at(-1) ?? null;
    return validateState({
      schemaVersion: SCHEMA_VERSION,
      activeTaskId: runtime.activeTaskId,
      tasks: units.map((unit) => unit.task),
      updatedAt,
    });
  }

  const { state } = repoPaths(repoRoot);
  if (!fs.existsSync(state)) throw new Error('DocFlow durable state is not initialized');
  return validateState(JSON.parse(fs.readFileSync(state, 'utf8')));
}

export function loadRuntime(repoRoot, exec = execFileSync) {
  const runtimeFile = runtimePath(repoRoot, exec);
  if (fs.existsSync(runtimeFile)) return validateRuntime(JSON.parse(fs.readFileSync(runtimeFile, 'utf8')));

  const legacy = repoPaths(repoRoot).runtime;
  if (fs.existsSync(legacy)) {
    const value = validateRuntime({ activeTaskId: null, ...JSON.parse(fs.readFileSync(legacy, 'utf8')) });
    return value;
  }
  return defaultRuntime();
}

function writeRuntime(repoRoot, runtime, exec = execFileSync) {
  const normalized = validateRuntime({ ...runtime });
  atomicWrite(runtimePath(repoRoot, exec), `${JSON.stringify(normalized, null, 2)}\n`);
  return normalized;
}

function durableUnitText(task, updatedAt) {
  const normalized = validateTask({ ...task, history: task.history.map((h) => ({ ...h })) });
  return `${JSON.stringify({ schemaVersion: SCHEMA_VERSION, updatedAt, task: normalized }, null, 2)}\n`;
}

function writeTaskUnit(repoRoot, task, {
  updatedAt = isoNow(), homeDir = os.homedir(), exec = execFileSync, message = null,
  expectedRevision = undefined,
} = {}) {
  const unitPath = stateUnitPath(task.id);
  return commitStateFiles({
    repoRoot,
    homeDir,
    exec,
    files: { [unitPath]: durableUnitText(task, updatedAt) },
    expectedFiles: expectedRevision === undefined ? null : { [unitPath]: expectedRevision },
    message: message || `DocFlow: update ${task.id}`,
    allowCreate: false,
  });
}

function readDurableProject(repoRoot, exec = execFileSync) {
  return readStateFile(repoRoot, DURABLE_PROJECT_PATH, exec);
}

function tasksEqual(a, b) {
  const left = validateTask({ ...a, history: a.history.map((h) => ({ ...h })) });
  const right = validateTask({ ...b, history: b.history.map((h) => ({ ...h })) });
  return JSON.stringify(left) === JSON.stringify(right);
}

export function initRepo({
  cwd = process.cwd(), projectName, summary = '', obsidianNote,
  now = new Date(), exec = execFileSync, homeDir = os.homedir(),
} = {}) {
  const repoRoot = resolveRepoRoot(cwd, exec);
  const paths = repoPaths(repoRoot);
  const legacyConfig = fs.existsSync(paths.config)
    ? normalizeRepoConfig(JSON.parse(fs.readFileSync(paths.config, 'utf8')))
    : null;
  const legacyState = fs.existsSync(paths.state)
    ? validateState(JSON.parse(fs.readFileSync(paths.state, 'utf8')))
    : null;
  const legacyRuntime = fs.existsSync(paths.runtime)
    ? validateRuntime({ activeTaskId: legacyState?.activeTaskId ?? null, ...JSON.parse(fs.readFileSync(paths.runtime, 'utf8')) })
    : null;
  const legacyProject = fs.existsSync(paths.project) ? fs.readFileSync(paths.project, 'utf8') : null;

  // A clone may predate creation of origin/docflow-state. Refresh it before
  // deciding whether this repository is already initialized so we never
  // reinitialize over durable state that exists only on the remote.
  refreshStateFromOrigin({ repoRoot, homeDir, exec });

  const durableText = durableConfigText(repoRoot, exec);
  const durableConfig = durableText == null ? null : normalizeRepoConfig(JSON.parse(durableText));
  const storeBefore = stateStoreStatus(repoRoot, exec);
  if (!durableConfig && storeBefore.readRef) {
    throw new Error(`Reserved branch ${STATE_BRANCH} exists but does not contain a valid DocFlow config`);
  }

  const name = clean(
    projectName || durableConfig?.projectName || legacyConfig?.projectName || path.basename(repoRoot),
    'projectName',
    { required: true, max: 200 },
  );
  const note = safeNotePath(
    obsidianNote || durableConfig?.obsidianNote || legacyConfig?.obsidianNote || `project - ${name.toLowerCase()}.md`,
  );
  const desiredConfig = { schemaVersion: SCHEMA_VERSION, projectName: name, obsidianNote: note };

  if (durableConfig) {
    if (projectName && durableConfig.projectName !== name) throw new Error('Project name conflicts with durable DocFlow config');
    if (obsidianNote && durableConfig.obsidianNote !== note) throw new Error('Obsidian note conflicts with durable DocFlow config');
  } else {
    const projectBody = legacyProject
      || `# ${name}\n\n## Project\n${clean(summary, 'summary', { max: 2000 }) || '-'}\n\n## Project principles\n-\n`;
    const files = {
      [DURABLE_CONFIG_PATH]: `${JSON.stringify(desiredConfig, null, 2)}\n`,
      [DURABLE_PROJECT_PATH]: projectBody.endsWith('\n') ? projectBody : `${projectBody}\n`,
    };
    if (legacyState) {
      for (const task of legacyState.tasks) {
        files[stateUnitPath(task.id)] = durableUnitText(task, legacyState.updatedAt || isoNow(now));
      }
    }
    commitStateFiles({
      repoRoot,
      files,
      message: 'DocFlow: initialize durable state',
      homeDir,
      exec,
      allowCreate: true,
    });
  }

  const migratedTaskIds = [];
  if (legacyState && durableConfig) {
    const files = {};
    for (const task of legacyState.tasks) {
      const unitPath = stateUnitPath(task.id);
      const existing = readStateFile(repoRoot, unitPath, exec);
      if (existing == null) {
        files[unitPath] = durableUnitText(task, legacyState.updatedAt || isoNow(now));
        migratedTaskIds.push(task.id);
        continue;
      }
      const durableUnit = parseDurableUnit(existing, unitPath);
      if (!tasksEqual(durableUnit.task, task)) {
        throw new Error(`Legacy DocFlow unit conflicts with durable state: ${task.id}`);
      }
    }
    if (Object.keys(files).length) {
      commitStateFiles({
        repoRoot,
        files,
        message: 'DocFlow: migrate legacy worktree units',
        homeDir,
        exec,
        allowCreate: false,
      });
    }
  } else if (legacyState) {
    migratedTaskIds.push(...legacyState.tasks.map((task) => task.id));
  }

  const currentRuntimePath = runtimePath(repoRoot, exec);
  if (!fs.existsSync(currentRuntimePath)) {
    const migratedRuntime = legacyRuntime || defaultRuntime();
    migratedRuntime.activeTaskId ??= legacyState?.activeTaskId ?? null;
    writeRuntime(repoRoot, migratedRuntime, exec);
  }

  const hadLegacy = fs.existsSync(paths.dir);
  if (hadLegacy) fs.rmSync(paths.dir, { recursive: true, force: true });

  const config = loadRepoConfig(repoRoot, exec);
  return {
    repoRoot,
    alreadyInitialized: Boolean(durableConfig),
    config,
    stateBranch: STATE_BRANCH,
    migratedLegacy: hadLegacy,
    migratedTaskIds,
    initializedAt: isoNow(now),
  };
}

export function startTask({
  cwd = process.cwd(), id, title, task, current = '', next = '', status = 'In progress',
  now = new Date(), exec = execFileSync, homeDir = os.homedir(),
} = {}) {
  const repoRoot = resolveRepoRoot(cwd, exec);
  if (!loadRepoConfig(repoRoot, exec)) throw new Error('DocFlow is not enabled in this repository');
  const taskId = clean(id, 'task id', { required: true, max: 120 });
  const unitPath = stateUnitPath(taskId);
  const expectedRevision = stateFileRevision(repoRoot, unitPath, exec);
  const state = loadState(repoRoot, exec);
  if (expectedRevision != null || state.tasks.some((entry) => entry.id === taskId)) {
    throw new Error(`Task already exists: ${taskId}`);
  }
  const entry = validateTask({
    id: taskId,
    title: clean(title, 'task title', { required: true, max: 300 }),
    task: clean(task, 'task description', { required: true, max: 2000 }),
    started: isoNow(now),
    status: canonicalStatus(status),
    current: clean(current, 'current', { max: 2000 }),
    next: clean(next, 'next', { max: 2000 }),
    history: [], completed: null, outcome: null,
  });
  writeTaskUnit(repoRoot, entry, {
    updatedAt: isoNow(now),
    homeDir,
    exec,
    message: `DocFlow: start ${taskId}`,
    expectedRevision,
  });
  const runtime = loadRuntime(repoRoot, exec);
  runtime.activeTaskId = taskId;
  writeRuntime(repoRoot, runtime, exec);
  return { repoRoot, task: entry, state: loadState(repoRoot, exec) };
}

function findTask(state, id) {
  const taskId = clean(id || state.activeTaskId, 'task id', { required: true, max: 120 });
  const task = state.tasks.find((entry) => entry.id === taskId);
  if (!task) throw new Error(`Unknown DocFlow task: ${taskId}`);
  return task;
}

export function beginRound({ cwd = process.cwd(), id, now = new Date(), exec = execFileSync } = {}) {
  const repoRoot = resolveRepoRoot(cwd, exec);
  const runtime = loadRuntime(repoRoot, exec);
  const state = loadState(repoRoot, exec);
  const task = findTask(state, id || runtime.activeTaskId);
  if (TERMINAL_STATUSES.has(task.status)) throw new Error(`Task ${task.id} is terminal (${task.status})`);
  const fingerprint = repositoryFingerprint(repoRoot, exec);
  if (runtime.activeSession) {
    if (runtime.activeSession.taskId === task.id && runtime.activeSession.baselineFingerprint === fingerprint) {
      return { repoRoot, session: runtime.activeSession, reused: true };
    }
    throw new Error(`DocFlow already has an uncheckpointed round for ${runtime.activeSession.taskId}`);
  }
  runtime.activeTaskId = task.id;
  runtime.activeSession = { taskId: task.id, startedAt: isoNow(now), baselineFingerprint: fingerprint };
  writeRuntime(repoRoot, runtime, exec);
  return { repoRoot, session: runtime.activeSession, reused: false };
}

export function checkpoint({
  cwd = process.cwd(), id, current, next = '', status, outcome,
  now = new Date(), exec = execFileSync, homeDir = os.homedir(),
} = {}) {
  const repoRoot = resolveRepoRoot(cwd, exec);
  const runtime = loadRuntime(repoRoot, exec);
  const explicitId = id == null ? null : clean(id, 'task id', { required: true, max: 120 });
  if (runtime.activeSession && explicitId && explicitId !== runtime.activeSession.taskId) {
    throw new Error(
      `Cannot checkpoint task ${explicitId} while an uncheckpointed round is active for ${runtime.activeSession.taskId}`,
    );
  }
  const targetId = clean(
    runtime.activeSession?.taskId || explicitId || runtime.activeTaskId,
    'task id',
    { required: true, max: 120 },
  );
  // Capture the unit revision before loading the mutable snapshot. If another
  // actor advances the unit before this checkpoint commits, the CAS precondition
  // below rejects the stale write instead of silently dropping Current/History.
  const expectedRevision = stateFileRevision(repoRoot, stateUnitPath(targetId), exec);
  const state = loadState(repoRoot, exec);
  const task = findTask(state, targetId);
  const newCurrent = clean(current, 'current', { required: true, max: 2000 });
  const newNext = clean(next, 'next', { max: 2000 });
  const newStatus = canonicalStatus(status ?? task.status);
  if (TERMINAL_STATUSES.has(task.status) && newStatus !== task.status) throw new Error(`Terminal task ${task.id} cannot be reopened in v1`);
  if (task.current && task.current !== newCurrent) {
    const last = task.history.at(-1)?.text;
    if (last !== task.current) task.history.push({ at: isoNow(now), text: task.current });
  }
  task.current = newCurrent;
  task.next = newNext;
  task.status = newStatus;
  if (TERMINAL_STATUSES.has(newStatus)) {
    task.completed ??= isoNow(now);
    task.outcome = outcome == null || !String(outcome).trim() ? task.outcome : clean(outcome, 'outcome', { max: 300 });
  } else if (outcome != null && String(outcome).trim()) {
    throw new Error('Outcome is only valid for a terminal task');
  }

  writeTaskUnit(repoRoot, task, {
    updatedAt: isoNow(now),
    homeDir,
    exec,
    message: `DocFlow: checkpoint ${task.id}`,
    expectedRevision,
  });

  // Projection is part of the checkpoint transaction. If the configured
  // Obsidian note lives inside this repository, write it before sealing the
  // repository fingerprint so the gate observes the exact post-checkpoint tree.
  const obsidian = syncObsidian({ cwd: repoRoot, homeDir, exec, taskId: task.id });

  const fingerprint = repositoryFingerprint(repoRoot, exec);
  runtime.activeTaskId = task.id;
  runtime.lastCheckpoint = { taskId: task.id, at: isoNow(now), fingerprint };
  runtime.activeSession = null;
  const savedRuntime = writeRuntime(repoRoot, runtime, exec);
  return { repoRoot, task, state: loadState(repoRoot, exec), runtime: savedRuntime, obsidian };
}

export function gateStatus({ cwd = process.cwd(), exec = execFileSync } = {}) {
  const repoRoot = resolveRepoRoot(cwd, exec);
  if (!loadRepoConfig(repoRoot, exec)) {
    return { repoRoot, enabled: false, status: 'DISABLED', reason: `repository has no DocFlow durable state on ${STATE_BRANCH}` };
  }
  const runtime = loadRuntime(repoRoot, exec);
  const fingerprint = repositoryFingerprint(repoRoot, exec);
  if (runtime.activeSession) {
    return { repoRoot, enabled: true, status: 'PENDING', reason: `uncheckpointed round for ${runtime.activeSession.taskId}`, taskId: runtime.activeSession.taskId };
  }
  if (!runtime.lastCheckpoint) {
    return { repoRoot, enabled: true, status: 'PENDING', reason: 'no successful checkpoint has been recorded yet', taskId: null };
  }
  if (runtime.lastCheckpoint.fingerprint !== fingerprint) {
    return { repoRoot, enabled: true, status: 'PENDING', reason: 'repository work changed after the last checkpoint', taskId: runtime.lastCheckpoint.taskId };
  }
  return { repoRoot, enabled: true, status: 'READY', reason: 'current repository work matches the last successful checkpoint', taskId: runtime.lastCheckpoint.taskId, checkpointAt: runtime.lastCheckpoint.at };
}

export function projectStatus({ cwd = process.cwd(), exec = execFileSync } = {}) {
  const repoRoot = resolveRepoRoot(cwd, exec);
  const config = loadRepoConfig(repoRoot, exec);
  if (!config) return { repoRoot, enabled: false, gate: gateStatus({ cwd: repoRoot, exec }) };
  const state = loadState(repoRoot, exec);
  return {
    repoRoot,
    enabled: true,
    config,
    state,
    stateStore: stateStoreStatus(repoRoot, exec),
    gate: gateStatus({ cwd: repoRoot, exec }),
  };
}

function unitMarkerKey(taskId) {
  return encodeURIComponent(clean(taskId, 'task id', { required: true, max: 120 }));
}

export function unitMarkers(taskId) {
  const key = unitMarkerKey(taskId);
  return {
    begin: `<!-- DOCFLOW:UNIT:${key}:START -->`,
    end: `<!-- DOCFLOW:UNIT:${key}:END -->`,
  };
}

function displayDate(value) {
  const text = String(value ?? '').trim();
  const match = /^(\d{4}-\d{2}-\d{2})T/.exec(text);
  return match ? match[1] : text;
}

export function renderTaskUnit(task) {
  const normalized = validateTask(JSON.parse(JSON.stringify(task)));
  const markers = unitMarkers(normalized.id);
  const lines = [markers.begin, `## ${normalized.id} · ${normalized.title}`, ''];
  lines.push(`**Task:** ${normalized.task}`);
  lines.push(`**Started:** ${displayDate(normalized.started)}`);
  lines.push(`**Status:** ${normalized.status}`);
  lines.push('');
  lines.push('**Current**', normalized.current || '-', '');
  lines.push('**Next**', normalized.next || '-', '');
  lines.push('**History**');
  if (normalized.history.length) {
    for (const entry of normalized.history) lines.push(`- ${entry.text}`);
  } else {
    lines.push('-');
  }
  if (normalized.completed) lines.push('', `**Completed:** ${displayDate(normalized.completed)}`);
  if (normalized.outcome) lines.push(`**Outcome:** ${normalized.outcome}`);
  lines.push(markers.end);
  return `${lines.join('\n')}\n`;
}

export function renderProgress(state) {
  const normalized = validateState(JSON.parse(JSON.stringify(state)));
  const lines = [MANAGED_BEGIN, GENERATED_NOTICE, ''];
  if (!normalized.tasks.length) {
    lines.push('_No DocFlow version/task records yet._');
  } else {
    for (const task of normalized.tasks) {
      lines.push(renderTaskUnit(task).trimEnd(), '');
    }
    while (lines.at(-1) === '') lines.pop();
  }
  lines.push(MANAGED_END);
  return `${lines.join('\n')}\n`;
}

function markerCount(text, marker) {
  return text.split(marker).length - 1;
}

function managedBounds(text) {
  const bc = markerCount(text, MANAGED_BEGIN);
  const ec = markerCount(text, MANAGED_END);
  if (bc !== 1 || ec !== 1) throw new Error('Refusing to update malformed or duplicate DocFlow managed block');
  const start = text.indexOf(MANAGED_BEGIN);
  const endStart = text.indexOf(MANAGED_END);
  if (endStart < start) throw new Error('Refusing to update malformed DocFlow managed block');
  return { start, innerStart: start + MANAGED_BEGIN.length, endStart, end: endStart + MANAGED_END.length };
}

export function upsertManagedBlock(existing, block) {
  const text = String(existing ?? '');
  const bc = markerCount(text, MANAGED_BEGIN);
  const ec = markerCount(text, MANAGED_END);
  if (bc === 0 && ec === 0) {
    const prefix = text.trimEnd();
    return `${prefix ? `${prefix}\n\n` : ''}${block.trimEnd()}\n`;
  }
  const bounds = managedBounds(text);
  return `${text.slice(0, bounds.start)}${block.trimEnd()}${text.slice(bounds.end)}`.replace(/\s*$/, '\n');
}

export function ensureManagedContainer(existing) {
  const text = String(existing ?? '');
  const bc = markerCount(text, MANAGED_BEGIN);
  const ec = markerCount(text, MANAGED_END);
  if (bc === 0 && ec === 0) {
    const block = `${MANAGED_BEGIN}\n${GENERATED_NOTICE}\n\n_No DocFlow version/task records yet._\n${MANAGED_END}\n`;
    const prefix = text.trimEnd();
    return `${prefix ? `${prefix}\n\n` : ''}${block}`;
  }
  managedBounds(text);
  return text;
}

function legacyUnitBounds(inner, taskId) {
  const prefix = `## ${taskId} · `;
  const matches = [];
  let cursor = 0;
  while (cursor < inner.length) {
    const index = inner.indexOf(prefix, cursor);
    if (index < 0) break;
    const atLineStart = index === 0 || inner[index - 1] === '\n';
    if (atLineStart) matches.push(index);
    cursor = index + prefix.length;
  }
  if (matches.length > 1) {
    throw new Error(`Refusing to migrate duplicate legacy DocFlow sections for ${taskId}`);
  }
  if (matches.length === 0) return null;

  const start = matches[0];
  const headingEnd = inner.indexOf('\n', start);
  if (headingEnd < 0) throw new Error(`Malformed legacy DocFlow section for ${taskId}`);
  const sectionBody = inner.slice(headingEnd + 1);
  if (!sectionBody.trimStart().startsWith('**Task:**')) {
    throw new Error(`Malformed legacy DocFlow section for ${taskId}`);
  }

  const nextHeading = inner.indexOf('\n## ', headingEnd + 1);
  const end = nextHeading < 0 ? inner.length : nextHeading + 1;
  return { start, end };
}

export function upsertManagedUnit(existing, task) {
  const normalized = validateTask(JSON.parse(JSON.stringify(task)));
  const unit = renderTaskUnit(normalized).trimEnd();
  const markers = unitMarkers(normalized.id);
  let text = ensureManagedContainer(existing);
  const bounds = managedBounds(text);

  const beginCount = markerCount(text, markers.begin);
  const endCount = markerCount(text, markers.end);
  if (beginCount !== endCount || beginCount > 1) {
    throw new Error(`Refusing to update malformed or duplicate DocFlow unit block for ${normalized.id}`);
  }

  if (beginCount === 1) {
    const start = text.indexOf(markers.begin, bounds.innerStart);
    const endStart = text.indexOf(markers.end, start);
    if (start < bounds.innerStart || endStart < start || endStart > bounds.endStart) {
      throw new Error(`Refusing to update malformed DocFlow unit block for ${normalized.id}`);
    }
    const end = endStart + markers.end.length;
    return `${text.slice(0, start)}${unit}${text.slice(end)}`;
  }

  let inner = text.slice(bounds.innerStart, bounds.endStart);
  const legacy = legacyUnitBounds(inner, normalized.id);
  if (legacy) {
    const before = inner.slice(0, legacy.start).trimEnd();
    const after = inner.slice(legacy.end).trimStart();
    const migrated = [before, unit, after].filter(Boolean).join('\n\n');
    return `${text.slice(0, bounds.innerStart)}\n${migrated}\n${text.slice(bounds.endStart)}`;
  }

  inner = inner.replace(/\n?\s*_No DocFlow version\/task records yet\._\s*/g, '\n');
  if (!inner.includes(GENERATED_NOTICE)) {
    inner = `\n${GENERATED_NOTICE}\n${inner.trim()}\n`;
  }
  inner = inner.trimEnd();
  const appended = `${inner}\n\n${unit}\n`;
  return `${text.slice(0, bounds.innerStart)}${appended}${text.slice(bounds.endStart)}`;
}

function sleepSync(milliseconds) {
  const buffer = new SharedArrayBuffer(4);
  Atomics.wait(new Int32Array(buffer), 0, 0, milliseconds);
}

function projectNoteLockPath(homeDir, target) {
  const key = createHash('sha256').update(path.resolve(target)).digest('hex');
  return path.join(homeDir, '.docflow', 'locks', `${key}.lock`);
}

function withProjectNoteLock(homeDir, target, fn, { timeoutMs = 5000, staleMs = 30000 } = {}) {
  const lockPath = projectNoteLockPath(homeDir, target);
  fs.mkdirSync(path.dirname(lockPath), { recursive: true, mode: 0o700 });
  const startedAt = Date.now();
  let descriptor = null;

  while (descriptor == null) {
    try {
      descriptor = fs.openSync(lockPath, 'wx', 0o600);
      fs.writeFileSync(descriptor, `${process.pid}\n`);
    } catch (error) {
      if (error?.code !== 'EEXIST') throw error;
      try {
        const stat = fs.statSync(lockPath);
        if (Date.now() - stat.mtimeMs > staleMs) {
          fs.unlinkSync(lockPath);
          continue;
        }
      } catch (statError) {
        if (statError?.code === 'ENOENT') continue;
        throw statError;
      }
      if (Date.now() - startedAt >= timeoutMs) {
        throw new Error(`Timed out waiting for DocFlow Project note lock: ${target}`);
      }
      sleepSync(25);
    }
  }

  try {
    return fn();
  } finally {
    try { fs.closeSync(descriptor); } catch { /* best effort */ }
    try { fs.unlinkSync(lockPath); } catch (error) {
      if (error?.code !== 'ENOENT') throw error;
    }
  }
}

export function globalConfigPath(homeDir = os.homedir()) {
  return path.join(homeDir, '.docflow', 'config.json');
}

export function configureGlobal({ homeDir = os.homedir(), vault, projectFolder = '02 Projects' } = {}) {
  const vaultPath = path.resolve(clean(vault, 'vault', { required: true, max: 1000 }));
  const folderRaw = clean(projectFolder, 'projectFolder', { required: true, max: 500 }).replaceAll('\\', '/');
  if (path.posix.isAbsolute(folderRaw)) throw new Error('projectFolder must be relative to the vault');
  const folder = path.posix.normalize(folderRaw);
  if (folder === '..' || folder.startsWith('../')) throw new Error('projectFolder may not escape the vault');
  const config = { schemaVersion: SCHEMA_VERSION, obsidian: { vault: vaultPath, projectFolder: folder } };
  atomicWrite(globalConfigPath(homeDir), `${JSON.stringify(config, null, 2)}\n`);
  return config;
}

export function loadGlobalConfig(homeDir = os.homedir()) {
  const file = globalConfigPath(homeDir);
  if (!fs.existsSync(file)) return null;
  const value = JSON.parse(fs.readFileSync(file, 'utf8'));
  if (!value || value.schemaVersion !== SCHEMA_VERSION || typeof value.obsidian !== 'object') throw new Error('Unsupported DocFlow global config');
  return configureShape(value);
}

function configureShape(value) {
  const vault = path.resolve(clean(value.obsidian?.vault, 'vault', { required: true, max: 1000 }));
  const folderRaw = clean(value.obsidian?.projectFolder, 'projectFolder', { required: true, max: 500 }).replaceAll('\\', '/');
  if (path.posix.isAbsolute(folderRaw)) throw new Error('projectFolder must be relative to the vault');
  const folder = path.posix.normalize(folderRaw);
  if (folder === '..' || folder.startsWith('../')) throw new Error('projectFolder may not escape the vault');
  return { schemaVersion: SCHEMA_VERSION, obsidian: { vault, projectFolder: folder } };
}

export function syncObsidian({
  cwd = process.cwd(), homeDir = os.homedir(), exec = execFileSync, taskId = null,
} = {}) {
  const repoRoot = resolveRepoRoot(cwd, exec);
  const repoConfig = loadRepoConfig(repoRoot, exec);
  if (!repoConfig) throw new Error('DocFlow is not enabled in this repository');
  const global = loadGlobalConfig(homeDir);
  if (!global) return { skipped: true, reason: 'global Obsidian location is not configured' };
  const state = loadState(repoRoot, exec);
  const projectSource = (readDurableProject(repoRoot, exec) || '').trim();
  const target = path.resolve(global.obsidian.vault, global.obsidian.projectFolder, repoConfig.obsidianNote);
  const allowedRoot = path.resolve(global.obsidian.vault, global.obsidian.projectFolder);
  if (target !== allowedRoot && !target.startsWith(`${allowedRoot}${path.sep}`)) throw new Error('Resolved Obsidian note escaped the configured project folder');

  const tasks = taskId == null ? state.tasks : [findTask(state, taskId)];

  return withProjectNoteLock(homeDir, target, () => {
    let created = false;
    let existing = '';
    if (fs.existsSync(target)) {
      existing = fs.readFileSync(target, 'utf8');
    } else {
      created = true;
      existing = `---\ntype: project\n---\n\n${projectSource ? `${projectSource}\n` : `# ${repoConfig.projectName}\n`}`;
    }

    let next = ensureManagedContainer(existing);
    for (const task of tasks) next = upsertManagedUnit(next, task);

    atomicWrite(target, next);
    return { skipped: false, created, path: target, updatedTaskIds: tasks.map((task) => task.id) };
  });
}
