import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { commitUnitSections } from './render.js';
import {
  STATE_BRANCH,
  commitStateFiles,
  listStateFiles,
  readStateFile,
  refreshStateFromOrigin,
  lockIsStale,
  GIT_TIMEOUT_MS,
  runtimePath,
  stateFileRevision,
  stateStoreStatus,
  resolveStateUnitPath,
  stateUnitPath,
  withStateLock,
} from './state-store.js';

export const SCHEMA_VERSION = 1;
export const DOCFLOW_DIR = '.docflow';
export const CONFIG_FILE = 'config.json';
export const STATE_FILE = 'state.json';
export const RUNTIME_FILE = 'runtime.json';
export const PROJECT_FILE = 'project.md';
export const MANAGED_BEGIN = '<!-- DOCFLOW:START -->';
export const MANAGED_END = '<!-- DOCFLOW:END -->';
export const GENERATED_NOTICE = '<!-- Generated by DocFlow. Edit the repository source, not this block. -->';
const DURABLE_CONFIG_PATH = '.docflow/config.json';
const DURABLE_PROJECT_PATH = '.docflow/project.md';
const DURABLE_UNITS_PREFIX = '.docflow/units';

export const STATUS_VALUES = new Set(['In progress', 'Waiting', 'Paused', 'Completed', 'Abandoned']);
// Single limit for unit ids, branch names, runtime/active ids and marker keys so state
// written by one operation is always readable and projectable by every other.
export const MAX_TASK_ID_LENGTH = 200;
const TERMINAL_STATUSES = new Set(['Completed', 'Abandoned']);

function clean(value, label, { required = false, max = 4000 } = {}) {
  const text = String(value ?? '').replace(/\0/g, '').trim();
  if (required && !text) throw new Error(`${label} is required`);
  if (text.length > max) throw new Error(`${label} exceeds ${max} characters`);
  return text;
}

function isoNow(now = new Date()) {
  return now instanceof Date ? now.toISOString() : new Date(now).toISOString();
}

function canonicalStatus(value, fallback = 'In progress') {
  const raw = clean(value ?? fallback, 'status', { required: true, max: 80 });
  const key = raw.toLowerCase().replace(/[_-]+/g, ' ').replace(/\s+/g, ' ');
  const aliases = new Map([
    ['in progress', 'In progress'], ['progress', 'In progress'], ['active', 'In progress'],
    ['waiting', 'Waiting'], ['waiting human', 'Waiting'], ['waiting for user', 'Waiting'],
    ['paused', 'Paused'], ['pause', 'Paused'],
    ['completed', 'Completed'], ['complete', 'Completed'], ['done', 'Completed'],
    ['abandoned', 'Abandoned'], ['cancelled', 'Abandoned'], ['canceled', 'Abandoned'],
  ]);
  const out = aliases.get(key) ?? raw;
  if (!STATUS_VALUES.has(out)) throw new Error(`Unsupported status: ${raw}`);
  return out;
}

export function atomicWrite(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true, mode: 0o700 });
  const temp = path.join(path.dirname(filePath), `.${path.basename(filePath)}.${process.pid}.${Date.now()}.tmp`);
  fs.writeFileSync(temp, content, { encoding: 'utf8', mode: 0o600 });
  fs.renameSync(temp, filePath);
}

export function resolveRepoRoot(cwd = process.cwd(), exec = execFileSync) {
  try {
    return String(exec('git', ['-C', path.resolve(cwd), 'rev-parse', '--show-toplevel'], {
      encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], timeout: GIT_TIMEOUT_MS, killSignal: 'SIGKILL',
    })).trim();
  } catch {
    throw new Error(`Not inside a git repository: ${path.resolve(cwd)}`);
  }
}

function gitOutput(repoRoot, args, exec = execFileSync, { allowFailure = false } = {}) {
  try {
    return String(exec('git', ['-C', repoRoot, ...args], {
      encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], maxBuffer: 32 * 1024 * 1024,
      timeout: GIT_TIMEOUT_MS, killSignal: 'SIGKILL',
    }) ?? '');
  } catch (error) {
    if (allowFailure) return '';
    const detail = error?.stderr ? String(error.stderr).trim() : error?.message;
    throw new Error(`git ${args.join(' ')} failed${detail ? `: ${detail}` : ''}`);
  }
}

export function repositoryFingerprint(repoRoot, exec = execFileSync) {
  const root = path.resolve(repoRoot);
  const excludes = ['.', ':(exclude).docflow', ':(exclude).docflow/**'];
  const head = gitOutput(root, ['rev-parse', 'HEAD'], exec, { allowFailure: true }).trim() || 'UNBORN';
  const status = gitOutput(root, ['status', '--porcelain=v1', '-z', '--untracked-files=all', '--', ...excludes], exec);
  const unstaged = head === 'UNBORN'
    ? gitOutput(root, ['diff', '--binary', '--', ...excludes], exec)
    : gitOutput(root, ['diff', '--binary', 'HEAD', '--', ...excludes], exec);
  const staged = gitOutput(root, ['diff', '--cached', '--binary', '--', ...excludes], exec);
  const hash = createHash('sha256').update(head).update('\0').update(status).update('\0').update(unstaged).update('\0').update(staged);

  for (const entry of status.split('\0').filter(Boolean)) {
    if (!entry.startsWith('?? ')) continue;
    const rel = entry.slice(3);
    if (!rel || rel === DOCFLOW_DIR || rel.startsWith(`${DOCFLOW_DIR}/`)) continue;
    const full = path.join(root, rel);
    try {
      const stat = fs.statSync(full);
      if (!stat.isFile()) continue;
      hash.update('\0UNTRACKED\0').update(rel).update('\0').update(String(stat.size)).update('\0');
      const fd = fs.openSync(full, 'r');
      try {
        const buffer = Buffer.allocUnsafe(1024 * 1024);
        let offset = 0;
        while (offset < stat.size) {
          const bytesRead = fs.readSync(fd, buffer, 0, Math.min(buffer.length, stat.size - offset), offset);
          if (bytesRead <= 0) break;
          hash.update(buffer.subarray(0, bytesRead));
          offset += bytesRead;
        }
      } finally {
        fs.closeSync(fd);
      }
    } catch {
      hash.update('\0MISSING\0').update(rel);
    }
  }
  return hash.digest('hex');
}

export function repoPaths(repoRoot) {
  const dir = path.join(repoRoot, DOCFLOW_DIR);
  return {
    dir,
    config: path.join(dir, CONFIG_FILE),
    state: path.join(dir, STATE_FILE),
    runtime: path.join(dir, RUNTIME_FILE),
    project: path.join(dir, PROJECT_FILE),
  };
}

function safeNotePath(value) {
  const note = clean(value, 'obsidianNote', { required: true, max: 300 }).replaceAll('\\', '/');
  if (path.posix.isAbsolute(note)) throw new Error('obsidianNote must be relative to the configured project folder');
  const normalized = path.posix.normalize(note);
  if (normalized === '..' || normalized.startsWith('../')) throw new Error('obsidianNote may not escape the project folder');
  if (!normalized.toLowerCase().endsWith('.md')) throw new Error('obsidianNote must be a Markdown file');
  return normalized;
}

export function defaultState() {
  return { schemaVersion: SCHEMA_VERSION, activeTaskId: null, tasks: [], updatedAt: null };
}

export function defaultRuntime() {
  return { schemaVersion: SCHEMA_VERSION, activeTaskId: null, activeSession: null, lastCheckpoint: null };
}

function normalizeIsoDate(value, label, { required = false } = {}) {
  const text = clean(value, label, { required, max: 80 });
  if (!text) return null;
  const d = new Date(text);
  if (Number.isNaN(d.getTime())) {
    throw new Error(`${label} must be a valid ISO-8601 date string: ${text}`);
  }
  return text;
}

// Strip the ref prefix first (GitHub sends refs/heads/<name>), then apply the id limit.
export function normalizeBranchName(branch) {
  const stripped = clean(branch, 'branch', { required: true, max: MAX_TASK_ID_LENGTH + 11 }).replace(/^refs\/heads\//, '');
  return clean(stripped, 'branch', { required: true, max: MAX_TASK_ID_LENGTH });
}

export function commitSubject(message) {
  const line = String(message ?? '').replace(/\r/g, '').split('\n').map((l) => l.trim()).find(Boolean) || '';
  return line.length > 2000 ? `${line.slice(0, 1999)}…` : line;
}

function validateCommitProgress(commit) {
  if (!commit || typeof commit !== 'object' || Array.isArray(commit)) throw new Error('Invalid commit progress event');
  const rawSha = clean(commit.sha, 'commit.sha', { required: true, max: 64 });
  if (!/^[0-9a-f]{7,64}$/i.test(rawSha)) throw new Error(`Invalid commit sha: ${rawSha}`);
  const sha = rawSha.toLowerCase();
  const branch = clean(commit.branch, 'commit.branch', { required: true, max: MAX_TASK_ID_LENGTH });
  const timestamp = normalizeIsoDate(commit.timestamp, 'commit.timestamp', { required: true });
  // The first non-empty line is the canonical progress text. Bodies and any optional
  // summary field are never promoted into progress.
  const message = commitSubject(clean(commit.message, 'commit.message', { required: true, max: 100000 }));
  if (!message) throw new Error('commit.message is required');
  return { sha, branch, timestamp, message };
}

function validatePullRequest(pr) {
  if (!pr || typeof pr !== 'object' || Array.isArray(pr)) throw new Error('Invalid PR metadata');
  const number = Number(pr.number);
  if (!Number.isInteger(number) || number <= 0) throw new Error('Invalid PR number');
  const state = clean(pr.state, 'pr.state', { required: true, max: 50 });
  const title = pr.title == null ? null : clean(pr.title, 'pr.title', { max: 300 });
  const url = pr.url == null ? null : clean(pr.url, 'pr.url', { max: 1000 });
  const merged = pr.merged == null ? undefined : Boolean(pr.merged);
  const mergedAt = pr.mergedAt == null ? null : normalizeIsoDate(pr.mergedAt, 'pr.mergedAt');
  const closedAt = pr.closedAt == null ? null : normalizeIsoDate(pr.closedAt, 'pr.closedAt');
  const updatedAt = pr.updatedAt == null ? null : normalizeIsoDate(pr.updatedAt, 'pr.updatedAt');
  return {
    number,
    state,
    ...(title ? { title } : {}),
    ...(url ? { url } : {}),
    ...(merged !== undefined ? { merged } : {}),
    ...(mergedAt ? { mergedAt } : {}),
    ...(closedAt ? { closedAt } : {}),
    ...(updatedAt ? { updatedAt } : {}),
  };
}

const BASELINE_BRANCHES = ['main', 'master'];

export function resolveBaseBranchName(repoRoot, exec = execFileSync, defaultBranch = null) {
  // An explicit name (CI clones have no origin/HEAD) wins over the symbolic-ref fallback.
  const explicit = String(defaultBranch ?? process.env.DOCFLOW_DEFAULT_BRANCH ?? '').trim().replace(/^refs\/heads\//, '');
  if (explicit) return explicit;
  const symRef = gitOutput(repoRoot, ['symbolic-ref', '--quiet', 'refs/remotes/origin/HEAD'], exec, { allowFailure: true }).trim();
  const prefix = 'refs/remotes/origin/';
  return symRef.startsWith(prefix) ? symRef.slice(prefix.length) : '';
}

export function isDevelopmentBranch(branch, { repoRoot = null, exec = execFileSync, defaultBranch = null } = {}) {
  const name = String(branch ?? '').trim().replace(/^refs\/heads\//, '');
  if (!name) return false;
  const excluded = new Set([...BASELINE_BRANCHES, STATE_BRANCH]);
  if (repoRoot || defaultBranch) {
    const base = repoRoot ? resolveBaseBranchName(repoRoot, exec, defaultBranch) : String(defaultBranch).trim().replace(/^refs\/heads\//, '');
    if (base) excluded.add(base);
  }
  return !excluded.has(name);
}

function validateTask(task) {
  if (!task || typeof task !== 'object' || Array.isArray(task)) throw new Error('Invalid DocFlow task');
  task.id = clean(task.id, 'task.id', { required: true, max: MAX_TASK_ID_LENGTH });
  task.title = clean(task.title, 'task.title', { required: true, max: 300 });
  task.task = clean(task.task, 'task.task', { required: true, max: 2000 });
  task.started = clean(task.started, 'task.started', { required: true, max: 80 });
  task.status = canonicalStatus(task.status);
  task.current = clean(task.current, 'task.current', { max: 2000 });
  task.next = clean(task.next, 'task.next', { max: 2000 });
  if (!Array.isArray(task.history) || task.history.length > 10000) throw new Error('Invalid DocFlow task history');
  task.history = task.history.map((entry) => {
    if (!entry || typeof entry !== 'object' || Array.isArray(entry)) throw new Error('Invalid DocFlow history entry');
    return { at: clean(entry.at, 'history.at', { required: true, max: 80 }), text: clean(entry.text, 'history.text', { required: true, max: 2000 }) };
  });
  task.completed = task.completed == null ? null : clean(task.completed, 'task.completed', { required: true, max: 80 });
  task.outcome = task.outcome == null ? null : clean(task.outcome, 'task.outcome', { required: true, max: 300 });

  if (task.branch != null) {
    task.branch = clean(task.branch, 'task.branch', { required: true, max: MAX_TASK_ID_LENGTH });
  }

  if (task.commits != null) {
    if (!Array.isArray(task.commits) || task.commits.length > 20000) throw new Error('Invalid DocFlow task commits');
    const seenShas = new Set();
    task.commits = task.commits.map((c) => {
      const validated = validateCommitProgress(c);
      if (seenShas.has(validated.sha)) throw new Error(`Duplicate commit SHA in task: ${validated.sha}`);
      seenShas.add(validated.sha);
      return validated;
    });
  }

  if (task.pr != null) {
    task.pr = validatePullRequest(task.pr);
  }

  return task;
}

export function validateState(state) {
  if (!state || typeof state !== 'object' || Array.isArray(state) || state.schemaVersion !== SCHEMA_VERSION) {
    throw new Error('Unsupported or invalid DocFlow state');
  }
  if (!Array.isArray(state.tasks) || state.tasks.length > 5000) throw new Error('Invalid DocFlow task list');
  const seen = new Set();
  state.tasks = state.tasks.map((task) => {
    const normalized = validateTask({ ...task });
    if (seen.has(normalized.id)) throw new Error(`Duplicate DocFlow task id: ${normalized.id}`);
    seen.add(normalized.id);
    return normalized;
  });
  state.activeTaskId = state.activeTaskId == null ? null : clean(state.activeTaskId, 'activeTaskId', { required: true, max: MAX_TASK_ID_LENGTH });
  if (state.activeTaskId && !seen.has(state.activeTaskId)) throw new Error('activeTaskId does not exist');
  state.updatedAt = state.updatedAt == null ? null : clean(state.updatedAt, 'updatedAt', { required: true, max: 80 });
  return state;
}

export function validateRuntime(runtime) {
  if (!runtime || typeof runtime !== 'object' || Array.isArray(runtime) || runtime.schemaVersion !== SCHEMA_VERSION) {
    throw new Error('Unsupported or invalid DocFlow runtime state');
  }
  runtime.activeTaskId = runtime.activeTaskId == null
    ? null
    : clean(runtime.activeTaskId, 'runtime.activeTaskId', { required: true, max: MAX_TASK_ID_LENGTH });
  for (const key of ['activeSession', 'lastCheckpoint']) {
    if (runtime[key] != null && (typeof runtime[key] !== 'object' || Array.isArray(runtime[key]))) throw new Error(`Invalid ${key}`);
  }
  return runtime;
}

function normalizeRepoConfig(value) {
  if (!value || typeof value !== 'object' || value.schemaVersion !== SCHEMA_VERSION) throw new Error('Unsupported DocFlow repo config');
  return {
    schemaVersion: SCHEMA_VERSION,
    projectName: clean(value.projectName, 'projectName', { required: true, max: 200 }),
    obsidianNote: safeNotePath(value.obsidianNote),
  };
}

function parseDurableUnit(text, source) {
  const value = JSON.parse(text);
  if (!value || typeof value !== 'object' || value.schemaVersion !== SCHEMA_VERSION || !value.task) {
    throw new Error(`Unsupported DocFlow durable unit: ${source}`);
  }
  return {
    task: validateTask({ ...value.task, history: Array.isArray(value.task.history) ? value.task.history.map((h) => ({ ...h })) : value.task.history }),
    updatedAt: clean(value.updatedAt, 'unit.updatedAt', { required: true, max: 80 }),
  };
}

function durableConfigText(repoRoot, exec = execFileSync) {
  return readStateFile(repoRoot, DURABLE_CONFIG_PATH, exec);
}

export function loadRepoConfig(repoRoot, exec = execFileSync) {
  const durable = durableConfigText(repoRoot, exec);
  if (durable != null) return normalizeRepoConfig(JSON.parse(durable));

  const { config } = repoPaths(repoRoot);
  if (!fs.existsSync(config)) return null;
  return normalizeRepoConfig(JSON.parse(fs.readFileSync(config, 'utf8')));
}

export function loadState(repoRoot, exec = execFileSync) {
  const durableConfig = durableConfigText(repoRoot, exec);
  if (durableConfig != null) {
    const runtime = loadRuntime(repoRoot, exec);
    const unitPaths = listStateFiles(repoRoot, DURABLE_UNITS_PREFIX, exec);
    const units = unitPaths.map((unitPath) => {
      const text = readStateFile(repoRoot, unitPath, exec);
      if (text == null) throw new Error(`Missing DocFlow durable unit: ${unitPath}`);
      return parseDurableUnit(text, unitPath);
    });
    const updatedAt = units.map((unit) => unit.updatedAt).sort().at(-1) ?? null;
    return validateState({
      schemaVersion: SCHEMA_VERSION,
      activeTaskId: runtime.activeTaskId,
      tasks: units.map((unit) => unit.task),
      updatedAt,
    });
  }

  const { state } = repoPaths(repoRoot);
  if (!fs.existsSync(state)) throw new Error('DocFlow durable state is not initialized');
  return validateState(JSON.parse(fs.readFileSync(state, 'utf8')));
}

export function loadRuntime(repoRoot, exec = execFileSync) {
  const runtimeFile = runtimePath(repoRoot, exec);
  if (fs.existsSync(runtimeFile)) return validateRuntime(JSON.parse(fs.readFileSync(runtimeFile, 'utf8')));

  const legacy = repoPaths(repoRoot).runtime;
  if (fs.existsSync(legacy)) {
    const value = validateRuntime({ activeTaskId: null, ...JSON.parse(fs.readFileSync(legacy, 'utf8')) });
    return value;
  }
  return defaultRuntime();
}

function writeRuntime(repoRoot, runtime, exec = execFileSync) {
  const normalized = validateRuntime({ ...runtime });
  atomicWrite(runtimePath(repoRoot, exec), `${JSON.stringify(normalized, null, 2)}\n`);
  return normalized;
}

function durableUnitText(task, updatedAt) {
  const normalized = validateTask({ ...task, history: task.history.map((h) => ({ ...h })) });
  return `${JSON.stringify({ schemaVersion: SCHEMA_VERSION, updatedAt, task: normalized }, null, 2)}\n`;
}

function writeTaskUnit(repoRoot, task, {
  updatedAt = isoNow(), homeDir = os.homedir(), exec = execFileSync, message = null,
  expectedRevision = undefined, beforeCommit = null,
} = {}) {
  const unitPath = resolveStateUnitPath(repoRoot, task.id, exec);
  return commitStateFiles({
    repoRoot,
    homeDir,
    exec,
    files: { [unitPath]: durableUnitText(task, updatedAt) },
    expectedFiles: expectedRevision === undefined ? null : { [unitPath]: expectedRevision },
    message: message || `DocFlow: update ${task.id}`,
    allowCreate: false,
    beforeCommit,
  });
}

function readDurableProject(repoRoot, exec = execFileSync) {
  return readStateFile(repoRoot, DURABLE_PROJECT_PATH, exec);
}

function tasksEqual(a, b) {
  const left = validateTask({ ...a, history: a.history.map((h) => ({ ...h })) });
  const right = validateTask({ ...b, history: b.history.map((h) => ({ ...h })) });
  return JSON.stringify(left) === JSON.stringify(right);
}

export function initRepo({
  cwd = process.cwd(), projectName, summary = '', obsidianNote,
  now = new Date(), exec = execFileSync, homeDir = os.homedir(),
} = {}) {
  const repoRoot = resolveRepoRoot(cwd, exec);
  const paths = repoPaths(repoRoot);
  const legacyConfig = fs.existsSync(paths.config)
    ? normalizeRepoConfig(JSON.parse(fs.readFileSync(paths.config, 'utf8')))
    : null;
  const legacyState = fs.existsSync(paths.state)
    ? validateState(JSON.parse(fs.readFileSync(paths.state, 'utf8')))
    : null;
  const legacyRuntime = fs.existsSync(paths.runtime)
    ? validateRuntime({ activeTaskId: legacyState?.activeTaskId ?? null, ...JSON.parse(fs.readFileSync(paths.runtime, 'utf8')) })
    : null;
  const legacyProject = fs.existsSync(paths.project) ? fs.readFileSync(paths.project, 'utf8') : null;

  // A clone may predate creation of origin/docflow-state. Refresh it before
  // deciding whether this repository is already initialized so we never
  // reinitialize over durable state that exists only on the remote.
  refreshStateFromOrigin({ repoRoot, homeDir, exec });

  const durableText = durableConfigText(repoRoot, exec);
  const durableConfig = durableText == null ? null : normalizeRepoConfig(JSON.parse(durableText));
  const storeBefore = stateStoreStatus(repoRoot, exec);
  if (!durableConfig && storeBefore.readRef) {
    throw new Error(`Reserved branch ${STATE_BRANCH} exists but does not contain a valid DocFlow config`);
  }

  const name = clean(
    projectName || durableConfig?.projectName || legacyConfig?.projectName || path.basename(repoRoot),
    'projectName',
    { required: true, max: 200 },
  );
  const note = safeNotePath(
    obsidianNote || durableConfig?.obsidianNote || legacyConfig?.obsidianNote || `project - ${name.toLowerCase()}.md`,
  );
  const desiredConfig = { schemaVersion: SCHEMA_VERSION, projectName: name, obsidianNote: note };

  if (durableConfig) {
    if (projectName && durableConfig.projectName !== name) throw new Error('Project name conflicts with durable DocFlow config');
    if (obsidianNote && durableConfig.obsidianNote !== note) throw new Error('Obsidian note conflicts with durable DocFlow config');
  } else {
    const projectBody = legacyProject
      || `# ${name}\n\n## Project\n${clean(summary, 'summary', { max: 2000 }) || '-'}\n\n## Project principles\n-\n`;
    const files = {
      [DURABLE_CONFIG_PATH]: `${JSON.stringify(desiredConfig, null, 2)}\n`,
      [DURABLE_PROJECT_PATH]: projectBody.endsWith('\n') ? projectBody : `${projectBody}\n`,
    };
    if (legacyState) {
      for (const task of legacyState.tasks) {
        files[resolveStateUnitPath(repoRoot, task.id, exec)] = durableUnitText(task, legacyState.updatedAt || isoNow(now));
      }
    }
    commitStateFiles({
      repoRoot,
      files,
      expectedFiles: {
        [DURABLE_CONFIG_PATH]: null,
        [DURABLE_PROJECT_PATH]: null,
      },
      message: 'DocFlow: initialize durable state',
      homeDir,
      exec,
      allowCreate: true,
    });
  }

  const migratedTaskIds = [];
  if (legacyState && durableConfig) {
    const files = {};
    const expectedFiles = {};
    for (const task of legacyState.tasks) {
      const unitPath = resolveStateUnitPath(repoRoot, task.id, exec);
      const existing = readStateFile(repoRoot, unitPath, exec);
      if (existing == null) {
        files[unitPath] = durableUnitText(task, legacyState.updatedAt || isoNow(now));
        expectedFiles[unitPath] = null;
        migratedTaskIds.push(task.id);
        continue;
      }
      const durableUnit = parseDurableUnit(existing, unitPath);
      if (!tasksEqual(durableUnit.task, task)) {
        throw new Error(`Legacy DocFlow unit conflicts with durable state: ${task.id}`);
      }
    }
    if (Object.keys(files).length) {
      commitStateFiles({
        repoRoot,
        files,
        expectedFiles,
        message: 'DocFlow: migrate legacy worktree units',
        homeDir,
        exec,
        allowCreate: false,
      });
    }
  } else if (legacyState) {
    migratedTaskIds.push(...legacyState.tasks.map((task) => task.id));
  }

  const currentRuntimePath = runtimePath(repoRoot, exec);
  if (!fs.existsSync(currentRuntimePath)) {
    const migratedRuntime = legacyRuntime || defaultRuntime();
    migratedRuntime.activeTaskId ??= legacyState?.activeTaskId ?? null;
    writeRuntime(repoRoot, migratedRuntime, exec);
  }

  const hadLegacy = fs.existsSync(paths.dir);
  if (hadLegacy) fs.rmSync(paths.dir, { recursive: true, force: true });

  const config = loadRepoConfig(repoRoot, exec);
  return {
    repoRoot,
    alreadyInitialized: Boolean(durableConfig),
    config,
    stateBranch: STATE_BRANCH,
    migratedLegacy: hadLegacy,
    migratedTaskIds,
    initializedAt: isoNow(now),
  };
}

export function startTask({
  cwd = process.cwd(), id, title, task, current = '', next = '', status = 'In progress',
  now = new Date(), exec = execFileSync, homeDir = os.homedir(),
} = {}) {
  const repoRoot = resolveRepoRoot(cwd, exec);
  if (!loadRepoConfig(repoRoot, exec)) throw new Error('DocFlow is not enabled in this repository');
  const taskId = clean(id, 'task id', { required: true, max: MAX_TASK_ID_LENGTH });
  const unitPath = resolveStateUnitPath(repoRoot, taskId, exec);
  const expectedRevision = stateFileRevision(repoRoot, unitPath, exec);
  const state = loadState(repoRoot, exec);
  if (expectedRevision != null || state.tasks.some((entry) => entry.id === taskId)) {
    throw new Error(`Task already exists: ${taskId}`);
  }
  const entry = validateTask({
    id: taskId,
    title: clean(title, 'task title', { required: true, max: 300 }),
    task: clean(task, 'task description', { required: true, max: 2000 }),
    started: isoNow(now),
    status: canonicalStatus(status),
    current: clean(current, 'current', { max: 2000 }),
    next: clean(next, 'next', { max: 2000 }),
    history: [], completed: null, outcome: null,
  });
  writeTaskUnit(repoRoot, entry, {
    updatedAt: isoNow(now),
    homeDir,
    exec,
    message: `DocFlow: start ${taskId}`,
    expectedRevision,
  });
  const runtime = loadRuntime(repoRoot, exec);
  runtime.activeTaskId = taskId;
  writeRuntime(repoRoot, runtime, exec);
  return { repoRoot, task: entry, state: loadState(repoRoot, exec) };
}

function findTask(state, id) {
  const taskId = clean(id || state.activeTaskId, 'task id', { required: true, max: MAX_TASK_ID_LENGTH });
  const task = state.tasks.find((entry) => entry.id === taskId);
  if (!task) throw new Error(`Unknown DocFlow task: ${taskId}`);
  return task;
}

export function beginRound({ cwd = process.cwd(), id, now = new Date(), exec = execFileSync } = {}) {
  const repoRoot = resolveRepoRoot(cwd, exec);
  const runtime = loadRuntime(repoRoot, exec);
  const state = loadState(repoRoot, exec);
  const task = findTask(state, id || runtime.activeTaskId);
  if (TERMINAL_STATUSES.has(task.status)) throw new Error(`Task ${task.id} is terminal (${task.status})`);
  const fingerprint = repositoryFingerprint(repoRoot, exec);
  if (runtime.activeSession) {
    if (runtime.activeSession.taskId === task.id && runtime.activeSession.baselineFingerprint === fingerprint) {
      return { repoRoot, session: runtime.activeSession, reused: true };
    }
    throw new Error(`DocFlow already has an uncheckpointed round for ${runtime.activeSession.taskId}`);
  }
  runtime.activeTaskId = task.id;
  runtime.activeSession = { taskId: task.id, startedAt: isoNow(now), baselineFingerprint: fingerprint };
  writeRuntime(repoRoot, runtime, exec);
  return { repoRoot, session: runtime.activeSession, reused: false };
}

export function checkpoint({
  cwd = process.cwd(), id, current, next = '', status, outcome,
  now = new Date(), exec = execFileSync, homeDir = os.homedir(),
} = {}) {
  const repoRoot = resolveRepoRoot(cwd, exec);
  const runtime = loadRuntime(repoRoot, exec);
  const explicitId = id == null ? null : clean(id, 'task id', { required: true, max: MAX_TASK_ID_LENGTH });
  if (runtime.activeSession && explicitId && explicitId !== runtime.activeSession.taskId) {
    throw new Error(
      `Cannot checkpoint task ${explicitId} while an uncheckpointed round is active for ${runtime.activeSession.taskId}`,
    );
  }
  const targetId = clean(
    runtime.activeSession?.taskId || explicitId || runtime.activeTaskId,
    'task id',
    { required: true, max: MAX_TASK_ID_LENGTH },
  );
  // Capture the unit revision before loading the mutable snapshot. If another
  // actor advances the unit before this checkpoint commits, the CAS precondition
  // below rejects the stale write instead of silently dropping Current/History.
  const expectedRevision = stateFileRevision(repoRoot, resolveStateUnitPath(repoRoot, targetId, exec), exec);
  const state = loadState(repoRoot, exec);
  const task = findTask(state, targetId);
  const newCurrent = clean(current, 'current', { required: true, max: 2000 });
  const newNext = clean(next, 'next', { max: 2000 });
  const newStatus = canonicalStatus(status ?? task.status);
  if (TERMINAL_STATUSES.has(task.status) && newStatus !== task.status) throw new Error(`Terminal task ${task.id} cannot be reopened in v1`);
  if (task.current && task.current !== newCurrent) {
    const last = task.history.at(-1)?.text;
    if (last !== task.current) task.history.push({ at: isoNow(now), text: task.current });
  }
  task.current = newCurrent;
  task.next = newNext;
  task.status = newStatus;
  if (TERMINAL_STATUSES.has(newStatus)) {
    task.completed ??= isoNow(now);
    task.outcome = outcome == null || !String(outcome).trim() ? task.outcome : clean(outcome, 'outcome', { max: 300 });
  } else if (outcome != null && String(outcome).trim()) {
    throw new Error('Outcome is only valid for a terminal task');
  }

  writeTaskUnit(repoRoot, task, {
    updatedAt: isoNow(now),
    homeDir,
    exec,
    message: `DocFlow: checkpoint ${task.id}`,
    expectedRevision,
  });

  // Projection is part of the checkpoint transaction. If the configured
  // Obsidian note lives inside this repository, write it before sealing the
  // repository fingerprint so the gate observes the exact post-checkpoint tree.
  const obsidian = syncObsidian({ cwd: repoRoot, homeDir, exec, taskId: task.id });

  const fingerprint = repositoryFingerprint(repoRoot, exec);
  runtime.activeTaskId = task.id;
  runtime.lastCheckpoint = { taskId: task.id, at: isoNow(now), fingerprint };
  runtime.activeSession = null;
  const savedRuntime = writeRuntime(repoRoot, runtime, exec);
  return { repoRoot, task, state: loadState(repoRoot, exec), runtime: savedRuntime, obsidian };
}

export function getBranchUnit(repoRoot, branch, exec = execFileSync) {
  const branchName = normalizeBranchName(branch);
  const state = loadState(repoRoot, exec);
  return state.tasks.find((t) => t.branch === branchName || (t.id === branchName && t.branch == null)) || null;
}

export function findCommitInState(repoRoot, sha, exec = execFileSync) {
  const targetSha = String(sha ?? '').trim().toLowerCase();
  if (!targetSha) return null;
  const state = loadState(repoRoot, exec);
  for (const task of state.tasks) {
    if (!Array.isArray(task.commits)) continue;
    const found = task.commits.find((c) => c.sha.toLowerCase() === targetSha);
    if (found) {
      return { task, commit: found };
    }
  }
  return null;
}

export function resolveFullCommitSha(repoRoot, shaOrRev, exec = execFileSync) {
  const rev = String(shaOrRev ?? '').trim();
  if (!rev) return '';
  const resolved = gitOutput(repoRoot, ['rev-parse', '--verify', '--quiet', `${rev}^{commit}`], exec, { allowFailure: true }).trim();
  return resolved.toLowerCase();
}

// Every resolvable baseline tip: the repository default branch (origin/HEAD) plus
// main/master, local and remote. A commit reachable from any of them is baseline work.
export function resolveBaseBranchShas(repoRoot, exec = execFileSync, defaultBranch = null) {
  const refs = [];
  const symRef = gitOutput(repoRoot, ['symbolic-ref', '--quiet', 'refs/remotes/origin/HEAD'], exec, { allowFailure: true }).trim();
  if (symRef) refs.push(symRef);
  const defaultName = resolveBaseBranchName(repoRoot, exec, defaultBranch);
  for (const name of new Set([defaultName, ...BASELINE_BRANCHES].filter(Boolean))) {
    refs.push(`refs/heads/${name}`, `refs/remotes/origin/${name}`);
  }
  const shas = new Set();
  for (const ref of refs) {
    const sha = gitOutput(repoRoot, ['rev-parse', '--verify', '--quiet', `${ref}^{commit}`], exec, { allowFailure: true }).trim();
    if (sha) shas.add(sha);
  }
  return [...shas];
}

function isCommitReachableFromBase(repoRoot, sha, exec = execFileSync, defaultBranch = null) {
  if (!sha) return false;
  const baseShas = resolveBaseBranchShas(repoRoot, exec, defaultBranch);
  if (!baseShas.length) {
    // If base branch cannot be resolved in git, fail closed: do not assume commits are unique
    return true;
  }
  for (const baseSha of baseShas) {
    try {
      exec('git', ['-C', repoRoot, 'merge-base', '--is-ancestor', sha, baseSha], { stdio: 'ignore' });
      return true;
    } catch (error) {
      // Exit code 1 means NOT ancestor of this base tip. Anything else (e.g. 128 for an
      // invalid object) fails closed.
      if (!(error && typeof error.status === 'number' && error.status === 1)) return true;
    }
  }
  return false;
}

export function createBranchUnit({
  cwd = process.cwd(),
  branch,
  now = new Date(),
  exec = execFileSync,
  homeDir = os.homedir(),
  defaultBranch = null,
} = {}) {
  const repoRoot = resolveRepoRoot(cwd, exec);
  if (!loadRepoConfig(repoRoot, exec)) throw new Error('DocFlow is not enabled in this repository');
  const branchName = normalizeBranchName(branch);
  if (!isDevelopmentBranch(branchName, { repoRoot, exec, defaultBranch })) {
    throw new Error(`Branch '${branchName}' is not a development branch`);
  }

  return withStateLock(repoRoot, homeDir, exec, () => {
    const unitPath = resolveStateUnitPath(repoRoot, branchName, exec);
    const expectedRevision = stateFileRevision(repoRoot, unitPath, exec);

    const existing = getBranchUnit(repoRoot, branchName, exec);
    if (existing) {
      return { repoRoot, task: existing, created: false };
    }

    // A branch must exist in Git and possess commits beyond base branch before creating a durable unit.
    // If the branch does not exist in git (tipSha is empty), or is freshly cut from main/master (no commits
    // of its own beyond base), or its tip commit is already recorded in durable state,
    // do not create an empty redundant unit.
    const tipSha = gitOutput(repoRoot, ['rev-parse', '--verify', '--quiet', `refs/heads/${branchName}^{commit}`], exec, { allowFailure: true }).trim();
    if (!tipSha) {
      return { repoRoot, task: null, created: false };
    }

    const tipRecorded = findCommitInState(repoRoot, tipSha, exec);
    if (tipRecorded) {
      return { repoRoot, task: tipRecorded.task, created: false };
    }

    // Fail closed: an unresolvable base, or a tip already on base, means the branch has no
    // commits of its own, so no empty unit is created.
    if (isCommitReachableFromBase(repoRoot, tipSha, exec, defaultBranch)) {
      return { repoRoot, task: null, created: false };
    }

    const entry = validateTask({
      id: branchName,
      branch: branchName,
      title: branchName,
      task: `Development branch: ${branchName}`,
      started: isoNow(now),
      status: 'In progress',
      current: '',
      next: '',
      history: [],
      commits: [],
      pr: null,
      completed: null,
      outcome: null,
    });

    try {
      writeTaskUnit(repoRoot, entry, {
        updatedAt: isoNow(now),
        homeDir,
        exec,
        message: `DocFlow: create branch unit ${branchName}`,
        expectedRevision,
      });
    } catch (error) {
      if (error?.message && error.message.includes('DocFlow durable state changed concurrently for')) {
        const latest = getBranchUnit(repoRoot, branchName, exec);
        if (latest) {
          return { repoRoot, task: latest, created: false };
        }
      }
      throw error;
    }

    return { repoRoot, task: entry, created: true };
  });
}

export function recordCommitProgress({
  cwd = process.cwd(),
  branch,
  commit,
  now = new Date(),
  exec = execFileSync,
  homeDir = os.homedir(),
  defaultBranch = null,
} = {}) {
  const repoRoot = resolveRepoRoot(cwd, exec);
  if (!loadRepoConfig(repoRoot, exec)) throw new Error('DocFlow is not enabled in this repository');
  const branchName = normalizeBranchName(branch);
  if (!isDevelopmentBranch(branchName, { repoRoot, exec, defaultBranch })) {
    return { repoRoot, ignored: true, reason: `Branch '${branchName}' is not a development branch` };
  }

  const validCommit = validateCommitProgress({ ...commit, branch: branchName });

  // Canonicalize commit SHA to full object ID and verify that the commit object exists in Git.
  // If the object does not exist or fails to resolve to a commit, reject the progress event fail-closed.
  const fullSha = resolveFullCommitSha(repoRoot, validCommit.sha, exec);
  if (!fullSha) {
    return { repoRoot, ignored: true, reason: `Commit '${validCommit.sha}' is invalid or does not exist in git` };
  }
  validCommit.sha = fullSha;

  const unitPath = resolveStateUnitPath(repoRoot, branchName, exec);

  // Pre-check outside lock for fast-path idempotency on already-recorded commits
  const initialGlobal = findCommitInState(repoRoot, validCommit.sha, exec);
  if (initialGlobal) {
    return {
      repoRoot,
      task: initialGlobal.task,
      commit: initialGlobal.commit,
      alreadyRecorded: true,
      created: false,
    };
  }

  return withStateLock(repoRoot, homeDir, exec, () => {
    // Observe the newest published state before deciding. The local lock only serializes
    // writers on this machine; across machines the fast-forward-only state push is the
    // linearization point, so (a) refresh first and (b) re-assert the dedup precondition
    // against the final synchronized parent right before the state commit (beforeCommit).
    refreshStateFromOrigin({ repoRoot, homeDir, exec });

    // Atomically re-check repository-wide deduplication inside the state lock.
    const existingGlobally = findCommitInState(repoRoot, validCommit.sha, exec);
    if (existingGlobally) {
      return {
        repoRoot,
        task: existingGlobally.task,
        commit: existingGlobally.commit,
        alreadyRecorded: true,
        created: false,
      };
    }

    const expectedRevision = stateFileRevision(repoRoot, unitPath, exec);

    let task = getBranchUnit(repoRoot, branchName, exec);
    let created = false;

    // Base reachability only guards creation of NEW units from baseline commits. A commit
    // for an already-known branch unit stays recordable even if delivery arrived after the
    // branch was merged and the commit became reachable from base.
    if (!task && isCommitReachableFromBase(repoRoot, validCommit.sha, exec, defaultBranch)) {
      return { repoRoot, ignored: true, reason: `Commit ${validCommit.sha.slice(0, 7)} is already reachable from base` };
    }

    if (!task) {
      task = validateTask({
        id: branchName,
        branch: branchName,
        title: branchName,
        task: `Development branch: ${branchName}`,
        started: validCommit.timestamp || isoNow(now),
        status: 'In progress',
        current: '',
        next: '',
        history: [],
        commits: [],
        pr: null,
        completed: null,
        outcome: null,
      });
      created = true;
    } else {
      task = JSON.parse(JSON.stringify(task));
    }

    task.commits = task.commits || [];

    // Double-check: re-check against the loaded unit's commits before appending
    const alreadyInUnit = task.commits.find((c) => c.sha.toLowerCase() === validCommit.sha.toLowerCase());
    if (alreadyInUnit) {
      return {
        repoRoot,
        task,
        commit: alreadyInUnit,
        alreadyRecorded: true,
        created: false,
      };
    }

    task.commits.push(validCommit);

    const newCurrent = validCommit.message;
    if (task.current && task.current !== newCurrent) {
      const last = task.history.at(-1)?.text;
      if (last !== task.current) {
        task.history.push({ at: validCommit.timestamp || isoNow(now), text: task.current });
      }
    }
    task.current = newCurrent;

    try {
      writeTaskUnit(repoRoot, task, {
        updatedAt: isoNow(now),
        homeDir,
        exec,
        message: `DocFlow: record commit ${validCommit.sha.slice(0, 7)} on ${branchName}`,
        expectedRevision,
        beforeCommit: () => {
          if (findCommitInState(repoRoot, validCommit.sha, exec)) {
            throw Object.assign(new Error('DocFlow commit already recorded by a concurrent writer'), { code: 'DOCFLOW_SHA_RECORDED' });
          }
        },
      });
    } catch (error) {
      if (error?.code === 'DOCFLOW_SHA_RECORDED') {
        const latest = findCommitInState(repoRoot, validCommit.sha, exec);
        return { repoRoot, task: latest.task, commit: latest.commit, alreadyRecorded: true, created: false };
      }
      if (error?.message && error.message.includes('DocFlow durable state changed concurrently for')) {
        // Re-read latest state: check both the target branch unit and repository-wide units
        const latestGlobal = findCommitInState(repoRoot, validCommit.sha, exec);
        if (latestGlobal) {
          return {
            repoRoot,
            task: latestGlobal.task,
            commit: latestGlobal.commit,
            alreadyRecorded: true,
            created: false,
          };
        }
      }
      // If the latest state does NOT contain this SHA, retain the true CAS conflict error
      throw error;
    }

    return {
      repoRoot,
      task,
      commit: validCommit,
      alreadyRecorded: false,
      created,
    };
  });
}

function isCasConflict(error) {
  return Boolean(error?.message && error.message.includes('DocFlow durable state changed concurrently for'));
}

/**
 * Record an ordered batch of commits (one push) for a branch unit in a single durable write.
 * Every distinct SHA becomes exactly one progress event; SHAs already recorded anywhere in the
 * repository are skipped. Text equality is never used for identity.
 */
export function recordCommitsProgress({
  cwd = process.cwd(),
  branch,
  commits,
  now = new Date(),
  exec = execFileSync,
  homeDir = os.homedir(),
  defaultBranch = null,
  // SHAs that ingestion PROVED belong to this branch although base now contains them
  // (commits introduced by a merge commit's second parent). Only these skip the baseline
  // filter when a unit is first created; everything else reachable from base stays excluded.
  branchOwnedShas = [],
} = {}) {
  const repoRoot = resolveRepoRoot(cwd, exec);
  if (!loadRepoConfig(repoRoot, exec)) throw new Error('DocFlow is not enabled in this repository');
  const branchName = normalizeBranchName(branch);
  if (!isDevelopmentBranch(branchName, { repoRoot, exec, defaultBranch })) {
    return { repoRoot, ignored: true, reason: `Branch '${branchName}' is not a development branch`, recorded: [], alreadyRecorded: [], rejected: [] };
  }
  if (!Array.isArray(commits)) throw new Error('commits must be an array');

  const rejected = [];
  const valid = [];
  const seenInput = new Set();
  for (const raw of commits) {
    // A commit that reached GitHub with an unusable message (empty, oversized) is still
    // progress: it is ingested under a stand-in subject instead of failing the whole push.
    let candidate;
    try {
      candidate = validateCommitProgress({
        ...raw, branch: branchName,
        message: commitSubject(String(raw?.message ?? '').slice(0, 20000)) || '(empty commit message)',
      });
    } catch (error) {
      rejected.push({ sha: String(raw?.sha ?? ''), reason: error.message });
      continue;
    }
    const fullSha = resolveFullCommitSha(repoRoot, candidate.sha, exec);
    if (!fullSha) {
      rejected.push({ sha: candidate.sha, reason: 'invalid or does not exist in git' });
      continue;
    }
    if (seenInput.has(fullSha)) continue;
    seenInput.add(fullSha);
    valid.push({ ...candidate, sha: fullSha });
  }

  return withStateLock(repoRoot, homeDir, exec, () => {
    let lastError = null;
    for (let attempt = 0; attempt < 3; attempt += 1) {
      // Observe the newest published state first; the fast-forward-only state push (plus the
      // beforeCommit assertion below) is what serializes writers across machines.
      refreshStateFromOrigin({ repoRoot, homeDir, exec });
      const unitPath = resolveStateUnitPath(repoRoot, branchName, exec);
      const expectedRevision = stateFileRevision(repoRoot, unitPath, exec);
      const state = loadState(repoRoot, exec);
      const owner = new Map();
      for (const unit of state.tasks) for (const c of unit.commits || []) owner.set(c.sha.toLowerCase(), unit.id);

      const alreadyRecorded = valid.filter((c) => owner.has(c.sha)).map((c) => ({ sha: c.sha, unitId: owner.get(c.sha) }));
      let pending = valid.filter((c) => !owner.has(c.sha));

      const existing = state.tasks.find((t) => t.branch === branchName || (t.id === branchName && t.branch == null)) || null;
      // Base reachability only guards creation of NEW units from baseline commits; a known
      // unit keeps accepting delayed commits even after the branch was merged.
      if (!existing) {
        const owned = new Set((branchOwnedShas || []).map((sha) => String(sha).toLowerCase()));
        pending = pending.filter((c) => owned.has(c.sha) || !isCommitReachableFromBase(repoRoot, c.sha, exec, defaultBranch));
      }

      if (!pending.length) {
        return {
          repoRoot, task: existing, created: false, recorded: [], alreadyRecorded, rejected,
          ...(existing ? {} : { ignored: true, reason: 'No new commits beyond base for a new branch unit' }),
        };
      }

      const task = existing ? JSON.parse(JSON.stringify(existing)) : validateTask({
        id: branchName, branch: branchName, title: branchName, task: `Development branch: ${branchName}`,
        started: pending[0].timestamp || isoNow(now), status: 'In progress', current: '', next: '',
        history: [], commits: [], pr: null, completed: null, outcome: null,
      });
      task.commits = task.commits || [];
      for (const c of pending) {
        // Each distinct SHA is its own progress event; the superseded Current always moves to
        // History even when two subjects are textually identical.
        if (task.current) task.history.push({ at: c.timestamp, text: task.current });
        task.commits.push(c);
        task.current = c.message;
      }

      try {
        writeTaskUnit(repoRoot, task, {
          updatedAt: isoNow(now), homeDir, exec, expectedRevision,
          message: `DocFlow: record ${pending.length} commit${pending.length === 1 ? '' : 's'} on ${branchName}`,
          beforeCommit: () => {
            const latest = loadState(repoRoot, exec);
            const taken = new Set(latest.tasks.flatMap((u) => (u.commits || []).map((c) => c.sha.toLowerCase())));
            if (pending.some((c) => taken.has(c.sha))) {
              throw Object.assign(new Error('DocFlow commit already recorded by a concurrent writer'), { code: 'DOCFLOW_SHA_RECORDED' });
            }
          },
        });
      } catch (error) {
        if (error?.code === 'DOCFLOW_SHA_RECORDED' || isCasConflict(error)) {
          lastError = error;
          continue; // re-read the newest state and recompute
        }
        throw error;
      }
      return { repoRoot, task, created: !existing, recorded: pending, alreadyRecorded, rejected };
    }
    throw lastError;
  });
}

export function recordPullRequestEvent({
  cwd = process.cwd(),
  branch,
  pr,
  now = new Date(),
  exec = execFileSync,
  homeDir = os.homedir(),
  defaultBranch = null,
  // The GitHub webhook action ('opened' | 'reopened' | 'synchronize' | 'closed'). Only a
  // genuine 'reopened' event may restore an abandoned unit.
  action = null,
} = {}) {
  const repoRoot = resolveRepoRoot(cwd, exec);
  if (!loadRepoConfig(repoRoot, exec)) throw new Error('DocFlow is not enabled in this repository');
  const branchName = normalizeBranchName(branch);
  if (!isDevelopmentBranch(branchName, { repoRoot, exec, defaultBranch })) {
    return { repoRoot, ignored: true, reason: `Branch '${branchName}' is not a development branch` };
  }

  const validPr = validatePullRequest(pr);

  const attemptOnce = () => {
    const unitPath = resolveStateUnitPath(repoRoot, branchName, exec);
    const expectedRevision = stateFileRevision(repoRoot, unitPath, exec);

    let task = getBranchUnit(repoRoot, branchName, exec);
    let created = false;

    if (!task) {
      // Before creating a durable unit from a PR event, verify that the branch exists in Git
      // and has commits beyond the base branch, and is not already recorded elsewhere.
      const tipSha = gitOutput(repoRoot, ['rev-parse', '--verify', '--quiet', `refs/heads/${branchName}^{commit}`], exec, { allowFailure: true }).trim();
      if (!tipSha) {
        return { repoRoot, ignored: true, reason: `Branch '${branchName}' does not exist in git` };
      }

      if (isCommitReachableFromBase(repoRoot, tipSha, exec, defaultBranch)) {
        return { repoRoot, ignored: true, reason: `Branch '${branchName}' tip is reachable from base branch` };
      }

      const tipRecorded = findCommitInState(repoRoot, tipSha, exec);
      if (tipRecorded) {
        return { repoRoot, ignored: true, reason: `Branch tip ${tipSha.slice(0, 7)} already recorded in unit '${tipRecorded.task.id}'` };
      }

      task = validateTask({
        id: branchName,
        branch: branchName,
        title: validPr.title || branchName,
        task: `Development branch: ${branchName}`,
        started: isoNow(now),
        status: 'In progress',
        current: '',
        next: '',
        history: [],
        commits: [],
        pr: validPr,
        completed: null,
        outcome: null,
      });
      created = true;
    } else {
      task = JSON.parse(JSON.stringify(task));
    }

    // Preserve existing merged state if already merged and incoming event is out-of-order
    const wasAlreadyMerged = Boolean(task.pr?.merged || task.status === 'Completed');
    const merged = validPr.merged !== undefined ? (validPr.merged || wasAlreadyMerged) : wasAlreadyMerged;

    // Ordering: GitHub stamps every event with the PR's updated_at. An event older than the
    // newest one already applied is stale and must not change the lifecycle (a merged event
    // is terminal and always applies).
    const lastAppliedAt = task.pr?.updatedAt ?? null;
    // A genuine reopen is judged against the recorded CLOSURE time, not delivery order: events
    // arrive out of order, so it may legitimately trail a newer synchronize. Without a provable
    // timestamp we cannot rule out a delayed delivery, so it is not applied.
    const canRestore = action === 'reopened' && validPr.state === 'open' && !merged
      && task.status === 'Abandoned' && Boolean(validPr.updatedAt)
      && (!task.completed || validPr.updatedAt >= task.completed);
    const unrestorableReopen = action === 'reopened' && task.status === 'Abandoned' && !canRestore;
    // Any other event older than the newest one already applied is stale (a merged event is
    // terminal and always applies). Stale events never rewrite the recorded PR state.
    const stale = !validPr.merged && !canRestore
      && Boolean(validPr.updatedAt && lastAppliedAt && validPr.updatedAt < lastAppliedAt);
    if ((stale || unrestorableReopen) && !created) {
      return { repoRoot, task, created: false, ignored: true, reason: 'Stale pull request event ignored (older than the last applied event or closure)' };
    }

    task.pr = {
      ...(task.pr || {}),
      ...validPr,
      merged,
      // The recorded PR time only moves forward.
      ...(lastAppliedAt && (!validPr.updatedAt || validPr.updatedAt < lastAppliedAt) ? { updatedAt: lastAppliedAt } : {}),
    };

    if (merged) {
      task.status = 'Completed';
      task.outcome = 'Merged';
      task.completed ??= validPr.mergedAt || isoNow(now);
    } else if (validPr.state === 'closed' && !merged) {
      if (task.status !== 'Completed') {
        task.status = 'Abandoned';
        task.outcome = 'Closed without merge';
        // A newer close (after a reopen) must record its own time; the same close replayed keeps it.
        task.completed = validPr.closedAt || task.completed || isoNow(now);
      }
    } else if (canRestore) {
      task.status = 'In progress';
      task.outcome = null;
      task.completed = null;
    }

    writeTaskUnit(repoRoot, task, {
      updatedAt: isoNow(now),
      homeDir,
      exec,
      message: `DocFlow: PR #${validPr.number} ${merged ? 'merged' : validPr.state} on ${branchName}`,
      expectedRevision,
    });

    return {
      repoRoot,
      task,
      created,
    };
  };

  return withStateLock(repoRoot, homeDir, exec, () => {
    // Same discipline as commit recording: observe the newest published state, and re-read it
    // when another writer (e.g. a concurrent push run for this branch) wins the race, so a
    // merged/closed event is never dropped on stale state.
    let lastError = null;
    for (let attempt = 0; attempt < 4; attempt += 1) {
      refreshStateFromOrigin({ repoRoot, homeDir, exec });
      try {
        return attemptOnce();
      } catch (error) {
        if (!isCasConflict(error)) throw error;
        lastError = error;
      }
    }
    throw lastError;
  });
}

export function gateStatus({ cwd = process.cwd(), exec = execFileSync } = {}) {
  const repoRoot = resolveRepoRoot(cwd, exec);
  if (!loadRepoConfig(repoRoot, exec)) {
    return { repoRoot, enabled: false, status: 'DISABLED', reason: `repository has no DocFlow durable state on ${STATE_BRANCH}` };
  }
  const runtime = loadRuntime(repoRoot, exec);
  const fingerprint = repositoryFingerprint(repoRoot, exec);
  if (runtime.activeSession) {
    return { repoRoot, enabled: true, status: 'PENDING', reason: `uncheckpointed round for ${runtime.activeSession.taskId}`, taskId: runtime.activeSession.taskId };
  }
  if (!runtime.lastCheckpoint) {
    return { repoRoot, enabled: true, status: 'PENDING', reason: 'no successful checkpoint has been recorded yet', taskId: null };
  }
  if (runtime.lastCheckpoint.fingerprint !== fingerprint) {
    return { repoRoot, enabled: true, status: 'PENDING', reason: 'repository work changed after the last checkpoint', taskId: runtime.lastCheckpoint.taskId };
  }
  return { repoRoot, enabled: true, status: 'READY', reason: 'current repository work matches the last successful checkpoint', taskId: runtime.lastCheckpoint.taskId, checkpointAt: runtime.lastCheckpoint.at };
}

export function projectStatus({ cwd = process.cwd(), exec = execFileSync } = {}) {
  const repoRoot = resolveRepoRoot(cwd, exec);
  const config = loadRepoConfig(repoRoot, exec);
  if (!config) return { repoRoot, enabled: false, gate: gateStatus({ cwd: repoRoot, exec }) };
  const state = loadState(repoRoot, exec);
  return {
    repoRoot,
    enabled: true,
    config,
    state,
    stateStore: stateStoreStatus(repoRoot, exec),
    gate: gateStatus({ cwd: repoRoot, exec }),
  };
}

function unitMarkerKey(taskId) {
  return encodeURIComponent(clean(taskId, 'task id', { required: true, max: MAX_TASK_ID_LENGTH }));
}

export function unitMarkers(taskId) {
  const key = unitMarkerKey(taskId);
  return {
    begin: `<!-- DOCFLOW:UNIT:${key}:START -->`,
    end: `<!-- DOCFLOW:UNIT:${key}:END -->`,
  };
}

function displayDate(value) {
  const text = String(value ?? '').trim();
  const match = /^(\d{4}-\d{2}-\d{2})T/.exec(text);
  return match ? match[1] : text;
}

export function renderTaskUnit(task) {
  const normalized = validateTask(JSON.parse(JSON.stringify(task)));
  const markers = unitMarkers(normalized.id);
  // Commit-native units use a compact branch-first presentation. Keep their durable
  // IDs and DOCFLOW:UNIT markers unchanged so old projected notes update in place.
  // Legacy v1 units retain the original presentation verbatim below.
  if (normalized.branch) {
    const view = normalized.commits?.length
      ? commitUnitSections(normalized)
      : {
        current: normalized.current || '-',
        next: normalized.next || '',
        history: normalized.history.map((e) => e.text),
      };
    const pr = normalized.pr;
    const prUrl = typeof pr?.url === 'string'
      && /^https:\/\/github\.com\/[\w.-]+\/[\w.-]+\/pull\/\d+$/.test(pr.url)
      ? pr.url : null;
    const prLabel = pr ? (prUrl ? `[#${pr.number}](${prUrl})` : `#${pr.number}`) : '';
    const status = normalized.outcome ? `${normalized.status} · ${normalized.outcome}` : normalized.status;
    const lines = [
      markers.begin,
      `## Branch: ${normalized.branch}`,
      '',
      `**Status:** ${status}`,
      `**PR:**${prLabel ? ` ${prLabel}` : ''}`,
      `**Started:** ${displayDate(normalized.started)}`,
    ];
    if (normalized.completed) lines.push(`**Completed:** ${displayDate(normalized.completed)}`);
    lines.push('', '### Current', view.current || '-');
    if (view.next && view.next.trim() && view.next !== '-') lines.push('', '### Next', view.next);
    if (view.history.length) {
      lines.push('', '### History');
      for (const text of view.history) lines.push(`- ${text}`);
    }
    lines.push(markers.end);
    return `${lines.join('\n')}\n`;
  }

  const lines = [markers.begin, `## ${normalized.id} · ${normalized.title}`, ''];
  lines.push(`**Task:** ${normalized.task}`);
  lines.push(`**Started:** ${displayDate(normalized.started)}`);
  lines.push(`**Status:** ${normalized.status}`);
  lines.push('');
  // Commit-native units (v2) are projected from commits[] (identity = SHA); v1 units from
  // current/history exactly as before.
  const view = normalized.commits?.length
    ? commitUnitSections(normalized)
    : {
      current: normalized.current || '-',
      next: normalized.next || '-',
      history: normalized.history.map((e) => e.text),
    };
  lines.push('**Current**', view.current, '');
  lines.push('**Next**', view.next, '');
  lines.push('**History**');
  if (view.history.length) {
    for (const text of view.history) lines.push(`- ${text}`);
  } else {
    lines.push('-');
  }
  if (normalized.completed) lines.push('', `**Completed:** ${displayDate(normalized.completed)}`);
  if (normalized.outcome) lines.push(`**Outcome:** ${normalized.outcome}`);
  lines.push(markers.end);
  return `${lines.join('\n')}\n`;
}

export function renderProgress(state) {
  const normalized = validateState(JSON.parse(JSON.stringify(state)));
  const lines = [MANAGED_BEGIN, GENERATED_NOTICE, ''];
  if (!normalized.tasks.length) {
    lines.push('_No DocFlow version/task records yet._');
  } else {
    for (const task of normalized.tasks) {
      lines.push(renderTaskUnit(task).trimEnd(), '');
    }
    while (lines.at(-1) === '') lines.pop();
  }
  lines.push(MANAGED_END);
  return `${lines.join('\n')}\n`;
}

function markerCount(text, marker) {
  return text.split(marker).length - 1;
}

function managedBounds(text) {
  const bc = markerCount(text, MANAGED_BEGIN);
  const ec = markerCount(text, MANAGED_END);
  if (bc !== 1 || ec !== 1) throw new Error('Refusing to update malformed or duplicate DocFlow managed block');
  const start = text.indexOf(MANAGED_BEGIN);
  const endStart = text.indexOf(MANAGED_END);
  if (endStart < start) throw new Error('Refusing to update malformed DocFlow managed block');
  return { start, innerStart: start + MANAGED_BEGIN.length, endStart, end: endStart + MANAGED_END.length };
}

export function upsertManagedBlock(existing, block) {
  const text = String(existing ?? '');
  const bc = markerCount(text, MANAGED_BEGIN);
  const ec = markerCount(text, MANAGED_END);
  if (bc === 0 && ec === 0) {
    const prefix = text.trimEnd();
    return `${prefix ? `${prefix}\n\n` : ''}${block.trimEnd()}\n`;
  }
  const bounds = managedBounds(text);
  return `${text.slice(0, bounds.start)}${block.trimEnd()}${text.slice(bounds.end)}`.replace(/\s*$/, '\n');
}

export function ensureManagedContainer(existing) {
  const text = String(existing ?? '');
  const bc = markerCount(text, MANAGED_BEGIN);
  const ec = markerCount(text, MANAGED_END);
  if (bc === 0 && ec === 0) {
    const block = `${MANAGED_BEGIN}\n${GENERATED_NOTICE}\n\n_No DocFlow version/task records yet._\n${MANAGED_END}\n`;
    const prefix = text.trimEnd();
    return `${prefix ? `${prefix}\n\n` : ''}${block}`;
  }
  managedBounds(text);
  return text;
}

function legacyUnitBounds(inner, taskId) {
  const prefix = `## ${taskId} · `;
  const matches = [];
  let cursor = 0;
  while (cursor < inner.length) {
    const index = inner.indexOf(prefix, cursor);
    if (index < 0) break;
    const atLineStart = index === 0 || inner[index - 1] === '\n';
    if (atLineStart) matches.push(index);
    cursor = index + prefix.length;
  }
  if (matches.length > 1) {
    throw new Error(`Refusing to migrate duplicate legacy DocFlow sections for ${taskId}`);
  }
  if (matches.length === 0) return null;

  const start = matches[0];
  const headingEnd = inner.indexOf('\n', start);
  if (headingEnd < 0) throw new Error(`Malformed legacy DocFlow section for ${taskId}`);
  const sectionBody = inner.slice(headingEnd + 1);
  if (!sectionBody.trimStart().startsWith('**Task:**')) {
    throw new Error(`Malformed legacy DocFlow section for ${taskId}`);
  }

  const nextHeading = inner.indexOf('\n## ', headingEnd + 1);
  const end = nextHeading < 0 ? inner.length : nextHeading + 1;
  return { start, end };
}

export function upsertManagedUnit(existing, task) {
  const normalized = validateTask(JSON.parse(JSON.stringify(task)));
  const unit = renderTaskUnit(normalized).trimEnd();
  const markers = unitMarkers(normalized.id);
  let text = ensureManagedContainer(existing);
  const bounds = managedBounds(text);

  const beginCount = markerCount(text, markers.begin);
  const endCount = markerCount(text, markers.end);
  if (beginCount !== endCount || beginCount > 1) {
    throw new Error(`Refusing to update malformed or duplicate DocFlow unit block for ${normalized.id}`);
  }

  if (beginCount === 1) {
    const start = text.indexOf(markers.begin, bounds.innerStart);
    const endStart = text.indexOf(markers.end, start);
    if (start < bounds.innerStart || endStart < start || endStart > bounds.endStart) {
      throw new Error(`Refusing to update malformed DocFlow unit block for ${normalized.id}`);
    }
    const end = endStart + markers.end.length;
    return `${text.slice(0, start)}${unit}${text.slice(end)}`;
  }

  let inner = text.slice(bounds.innerStart, bounds.endStart);
  const legacy = legacyUnitBounds(inner, normalized.id);
  if (legacy) {
    const before = inner.slice(0, legacy.start).trimEnd();
    const after = inner.slice(legacy.end).trimStart();
    const migrated = [before, unit, after].filter(Boolean).join('\n\n');
    return `${text.slice(0, bounds.innerStart)}\n${migrated}\n${text.slice(bounds.endStart)}`;
  }

  inner = inner.replace(/\n?\s*_No DocFlow version\/task records yet\._\s*/g, '\n');
  if (!inner.includes(GENERATED_NOTICE)) {
    inner = `\n${GENERATED_NOTICE}\n${inner.trim()}\n`;
  }
  inner = inner.trimEnd();
  const appended = `${inner}\n\n${unit}\n`;
  return `${text.slice(0, bounds.innerStart)}${appended}${text.slice(bounds.endStart)}`;
}

function sleepSync(milliseconds) {
  const buffer = new SharedArrayBuffer(4);
  Atomics.wait(new Int32Array(buffer), 0, 0, milliseconds);
}

function projectNoteLockPath(homeDir, target) {
  const key = createHash('sha256').update(path.resolve(target)).digest('hex');
  return path.join(homeDir, '.docflow', 'locks', `${key}.lock`);
}

function withProjectNoteLock(homeDir, target, fn, { timeoutMs = 5000, staleMs = 30000 } = {}) {
  const lockPath = projectNoteLockPath(homeDir, target);
  fs.mkdirSync(path.dirname(lockPath), { recursive: true, mode: 0o700 });
  const startedAt = Date.now();
  let descriptor = null;

  while (descriptor == null) {
    try {
      descriptor = fs.openSync(lockPath, 'wx', 0o600);
      fs.writeFileSync(descriptor, `${process.pid}\n`);
    } catch (error) {
      if (error?.code !== 'EEXIST') throw error;
      try {
        if (lockIsStale(lockPath, staleMs)) {
          fs.unlinkSync(lockPath);
          continue;
        }
      } catch (statError) {
        if (statError?.code === 'ENOENT') continue;
        throw statError;
      }
      if (Date.now() - startedAt >= timeoutMs) {
        throw new Error(`Timed out waiting for DocFlow Project note lock: ${target}`);
      }
      sleepSync(25);
    }
  }

  try {
    return fn();
  } finally {
    try { fs.closeSync(descriptor); } catch { /* best effort */ }
    try { fs.unlinkSync(lockPath); } catch (error) {
      if (error?.code !== 'ENOENT') throw error;
    }
  }
}

export function globalConfigPath(homeDir = os.homedir()) {
  return path.join(homeDir, '.docflow', 'config.json');
}

export function configureGlobal({ homeDir = os.homedir(), vault, projectFolder = '02 Projects' } = {}) {
  const vaultPath = path.resolve(clean(vault, 'vault', { required: true, max: 1000 }));
  const folderRaw = clean(projectFolder, 'projectFolder', { required: true, max: 500 }).replaceAll('\\', '/');
  if (path.posix.isAbsolute(folderRaw)) throw new Error('projectFolder must be relative to the vault');
  const folder = path.posix.normalize(folderRaw);
  if (folder === '..' || folder.startsWith('../')) throw new Error('projectFolder may not escape the vault');
  const config = { schemaVersion: SCHEMA_VERSION, obsidian: { vault: vaultPath, projectFolder: folder } };
  atomicWrite(globalConfigPath(homeDir), `${JSON.stringify(config, null, 2)}\n`);
  return config;
}

export function loadGlobalConfig(homeDir = os.homedir()) {
  const file = globalConfigPath(homeDir);
  if (!fs.existsSync(file)) return null;
  const value = JSON.parse(fs.readFileSync(file, 'utf8'));
  if (!value || value.schemaVersion !== SCHEMA_VERSION || typeof value.obsidian !== 'object') throw new Error('Unsupported DocFlow global config');
  return configureShape(value);
}

function configureShape(value) {
  const vault = path.resolve(clean(value.obsidian?.vault, 'vault', { required: true, max: 1000 }));
  const folderRaw = clean(value.obsidian?.projectFolder, 'projectFolder', { required: true, max: 500 }).replaceAll('\\', '/');
  if (path.posix.isAbsolute(folderRaw)) throw new Error('projectFolder must be relative to the vault');
  const folder = path.posix.normalize(folderRaw);
  if (folder === '..' || folder.startsWith('../')) throw new Error('projectFolder may not escape the vault');
  return { schemaVersion: SCHEMA_VERSION, obsidian: { vault, projectFolder: folder } };
}

export function syncObsidian({
  cwd = process.cwd(), homeDir = os.homedir(), exec = execFileSync, taskId = null,
} = {}) {
  const repoRoot = resolveRepoRoot(cwd, exec);
  const repoConfig = loadRepoConfig(repoRoot, exec);
  if (!repoConfig) throw new Error('DocFlow is not enabled in this repository');
  const global = loadGlobalConfig(homeDir);
  if (!global) return { skipped: true, reason: 'global Obsidian location is not configured' };
  const state = loadState(repoRoot, exec);
  const projectSource = (readDurableProject(repoRoot, exec) || '').trim();
  const target = path.resolve(global.obsidian.vault, global.obsidian.projectFolder, repoConfig.obsidianNote);
  const allowedRoot = path.resolve(global.obsidian.vault, global.obsidian.projectFolder);
  if (target !== allowedRoot && !target.startsWith(`${allowedRoot}${path.sep}`)) throw new Error('Resolved Obsidian note escaped the configured project folder');

  const tasks = taskId == null ? state.tasks : [findTask(state, taskId)];

  return withProjectNoteLock(homeDir, target, () => {
    let created = false;
    let existing = '';
    if (fs.existsSync(target)) {
      existing = fs.readFileSync(target, 'utf8');
    } else {
      created = true;
      existing = `---\ntype: project\n---\n\n${projectSource ? `${projectSource}\n` : `# ${repoConfig.projectName}\n`}`;
    }

    let next = ensureManagedContainer(existing);
    for (const task of tasks) next = upsertManagedUnit(next, task);

    // Identical content is never rewritten: no new mtime, no churn for Obsidian/iCloud/Spotlight.
    const unchanged = !created && next === existing;
    if (!unchanged) atomicWrite(target, next);
    return { skipped: false, created, unchanged, path: target, updatedTaskIds: tasks.map((task) => task.id) };
  });
}
